/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-12-01 02:22:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src.jsp.index;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hoseo.gallery.GalleryDto;
import java.util.*;
import com.hoseo.util.StringUtil;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/src/jsp/index/../../include/footer.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/index/../../include/common.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/index/../../include/head.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/index/../../include/header.jsp", Long.valueOf(1417078158611L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write('\n');
      out.write('\n');
      out.write('\n');

	//상대경로 대용
	String commonURL="/hoseo";

      out.write("\n");
      out.write("\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\t<title>Hoseo Community</title>\n");
      out.write("\t\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/templatemo_style.css\" type=\"text/css\"/>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/top_navi.css\" type=\"text/css\"/>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/button.css\" type=\"text/css\"/>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/img_expend.css\" type=\"text/css\" media=\"screen\"/>\n");
      out.write("\n");
      out.write("\t<!--<script src=\"http://code.jqeury.com/jqeury-latest.min.js\"></script> -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/naviSlider_imgModal.js\"></script>\t\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/top_navi_silder.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<!-- 상단 메뉴 드롭다운 -->\n");
      out.write("\t<script language=\"javascript\" type=\"text/javascript\">\n");
      out.write("\t\tddsmoothmenu.init({\n");
      out.write("\t\t\tmainmenuid: \"templatemo_menu\", //menu DIV id\n");
      out.write("\t\t\torientation: 'h', //Horizontal or vertical menu: Set to \"h\" or \"v\"\n");
      out.write("\t\t\tclassname: 'ddsmoothmenu', //class added to menu's outer DIV\n");
      out.write("\t\t\t//customtheme: [\"#1c5a80\", \"#18374a\"],\n");
      out.write("\t\t\tcontentsource: \"markup\" //\"markup\" or [\"container_id\", \"path_to_menu_file\"]\n");
      out.write("\t\t})\n");
      out.write("\n");
      out.write("\t\tfunction clearText(field)\n");
      out.write("\t\t{\n");
      out.write("    \t\tif (field.defaultValue == field.value) \n");
      out.write("    \t\t\tfield.value = '';\n");
      out.write("    \t\telse if (field.value == '') \n");
      out.write("    \t\t\tfield.value = field.defaultValue;\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\t\n");
      out.write("\t<script type=\"text/JavaScript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/img_modal.js\"></script>");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/index_slider_1.css\"\ttype=\"text/css\" media=\"screen\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/index_slider_2.css\"\ttype=\"text/css\" media=\"screen\" />\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div id=\"templatemo_wrapper\">\n");
      out.write("\n");
      out.write("\t\t");
      out.write('\n');
      out.write('\n');
      out.write('\n');

	String userid = StringUtil.convNull(
			(String) session.getAttribute("userid"), "");
	String username = StringUtil.convNull(
			(String) session.getAttribute("username"), "");
	String layout = StringUtil.convNull(
			(String) request.getAttribute("layout"), "index");

	System.out.println("Session_userid : " + userid);
	System.out.println("Session_username : " + username);
	System.out.println(layout);
	
	
	

      out.write("\n");
      out.write("<!-- Start_header -->\n");
      out.write("<div id=\"templatemo_header\">\n");
      out.write("\t<div id=\"site_title\">\n");
      out.write("\t\t<img src=\"");
      out.print(commonURL);
      out.write("/src/images/add/intro_tex02.jpg\"\n");
      out.write("\t\t\talt=\"Venture1st_호서대학교\" />\n");
      out.write("\t</div>\n");
      out.write("\t<div align=\"right\" style=\"color: orange;\">\n");
      out.write("\t\t이 웹페이지는 <a\n");
      out.write("\t\t\thref=\"https://www.google.com/intl/ko/chrome/browser/features.html\">Chrome</a>\n");
      out.write("\t\t브라우저에 최적화 되어 있습니다\n");
      out.write("\t</div>\n");
      out.write("\t</a>\n");
      out.write("\t<div id=\"templatemo_search\">\n");
      out.write("\t\t<form action=\"search.do\" method=\"get\">\n");
      out.write("\t\t\t<input type=\"text\" value=\"Search...\" name=\"keyword\" id=\"keyword\"\n");
      out.write("\t\t\t\ttitle=\"keyword\" onfocus=\"clearText(this)\" onblur=\"clearText(this)\"\n");
      out.write("\t\t\t\tclass=\"txt_field\" /> <input type=\"submit\" name=\"Search\" value=\"\"\n");
      out.write("\t\t\t\talt=\"Search\" id=\"searchbutton\" title=\"Search\" class=\"sub_btn\" />\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!-- End_header -->\n");
      out.write("\n");

	

      out.write("\n");
      out.write("\n");
      out.write("<!-- Start Menu -->\n");
      out.write("<div id=\"templatemo_menu\" class=\"ddsmoothmenu\">\n");
      out.write("\t<ul>\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/index.do\"\n");
      out.write("\t\t\t");
if (layout.equals("index")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Home</a></li>\n");
      out.write("\t\t<li><a\n");
      out.write("\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=trade&pg=1&block=1\"\n");
      out.write("\t\t\t");
if (layout.equals("market")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Market\n");
      out.write("\t\t\t\tPlace</a>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=trade&pg=1&block=1\">중고\n");
      out.write("\t\t\t\t\t\t거래</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=ad&pg=1&block=1\">원룸 광고</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=report&pg=1&block=1\">사건/사고\n");
      out.write("\t\t\t\t\t\t신고</a></li>\n");
      out.write("\t\t\t</ul></li>\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=free&pg=1&block=1\"\n");
      out.write("\t\t\t");
if (layout.equals("board")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Board</a>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=free&pg=1&block=1\">자유게시판</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=none&pg=1&block=1\">익명게시판</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=missing&pg=1&block=1\">분실/습득물</a></li>\n");
      out.write("\t\t\t</ul></li>\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/gallery/list.do?pg=1&block=1\"\n");
      out.write("\t\t\t");
if (layout.equals("gallery")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Gallery</a></li>\n");
      out.write("\t\t<!-- <li><a href=\"blog.jsp\">Blog</a></li> -->\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/contact.do\"\n");
      out.write("\t\t\t");
if (layout.equals("contact")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Contact</a></li>\n");
      out.write("\t</ul>\n");
      out.write("\n");
      out.write("\t");

		if (!userid.equals("")) {
	
      out.write("\n");
      out.write("\t<div align=\"right\">\n");
      out.write("\t\t<div style=\"color: #fff\">\n");
      out.write("\t\t\t");
      out.print(username);
      out.write("&nbsp;님&nbsp;\n");
      out.write("\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/message/message_receive.do\">마이페이지</a>&nbsp;&nbsp;&nbsp; \n");
      out.write("\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/member/logout.do\" class=\"button button-blue\"><span>로그아웃</span></a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t");

		} else {
	
      out.write("\n");
      out.write("\t<div align=\"right\">\n");
      out.write("\t\t<a href=\"");
      out.print(commonURL);
      out.write("/member/login.do\" class=\"button button-blue\"><span>로그인</span></a>\n");
      out.write("\t\t<a href=\"");
      out.print(commonURL);
      out.write("/member/register.do\" class=\"button button-blue\"><span>회원가입</span></a>\n");
      out.write("\t</div>\n");
      out.write("\t");

		}
	
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<br style=\"clear: left\" />\n");
      out.write("</div>\n");
      out.write("<!-- End Menu -->");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!-- 메인 이미지 슬라이더 : 시작 -->\n");
      out.write("\t\t<div id=\"templatemo_slider\">\n");
      out.write("\t\t\t<div class=\"slider-wrapper theme-orman\">\n");
      out.write("\t\t\t\t<div class=\"ribbon\"></div> <!-- 테두리 설정 -->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- 슬라이더에 사용할 이미지 설정 -->\n");
      out.write("\t\t\t\t<div id=\"slider\" class=\"nivoSlider\">\n");
      out.write("\t\t\t\t\t<a rel=\"nofollow\" href=\"http://www.hoseo.ac.kr/CmsHome/intro_00022875.eznic\" target=\"_blank\"> \n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(commonURL);
      out.write("/src/images/slider/05.jpg\" alt=\"학교 전경\"\ttitle=\"이미지 클릭 시 대학 홈페이지로 이동합니다\" />\n");
      out.write("\t\t\t\t\t</a> \n");
      out.write("\t\t\t\t\t<a rel=\"nofollow\" href=\"http://www.hoseo.ac.kr/CmsHome/intro_00022875.eznic\" target=\"_blank\"> \n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(commonURL);
      out.write("/src/images/slider/02.jpg\" alt=\"교훈 : 하면된다. 할수있다.\" title=\"이미지 클릭 시 대학 홈페이지로 이동합니다\" />\n");
      out.write("\t\t\t\t\t</a> \n");
      out.write("\t\t\t\t\t<a rel=\"nofollow\" href=\"http://www.hoseo.ac.kr/CmsHome/intro_00022875.eznic\" target=\"_blank\"> \n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(commonURL);
      out.write("/src/images/slider/03.jpg\" alt=\"중앙도서관과 잔디광장\" \ttitle=\"이미지 클릭 시 대학 홈페이지로 이동합니다\" />\n");
      out.write("\t\t\t\t\t</a> \n");
      out.write("\t\t\t\t\t<a rel=\"nofollow\" href=\"http://www.hoseo.ac.kr/CmsHome/intro_00022875.eznic\" target=\"_blank\"> \n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(commonURL);
      out.write("/src/images/slider/06.jpg\" alt=\"장영실관\" title=\"이미지 클릭 시 대학 홈페이지로 이동합니다\" />\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"nivo-controlNav-bg\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- 메인 이미지 슬라이더 : 끝 -->\n");
      out.write("\n");
      out.write("\t\t<!-- Start main -->\n");
      out.write("\t\t<div id=\"templatemo_main\">\n");
      out.write("\t\t\t<h2>About</h2>\n");
      out.write("\t\t\t<div class=\"img_frame img_frame_12 img_nom img_fl\">\n");
      out.write("\t\t\t\t<span></span> <img src=\"");
      out.print(commonURL);
      out.write("/src/images/add/about.jpg\"\n");
      out.write("\t\t\t\t\talt=\"\" />\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"half right\">\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<em>기존의 <a\n");
      out.write("\t\t\t\t\t\thref=\"http://www.hoseo.ac.kr/CmsHome/communication_08.eznic\"\n");
      out.write("\t\t\t\t\t\ttarget=\"_blank\">호서광장 - 벼룩시장</a> 은 학번이 없는 사용자는\t글쓰기가 불가능했고, 커뮤니케이션<br/> 기능이 부족해 많은 호서인들이 사용하기엔 적합하지 않은 게시판이었습니다.\n");
      out.write("\t\t\t\t\t\t<br/><b>'호서 커뮤니티'</b>는 좀 더 자유로운 대학 게시판을 활성화 하기 위해 만들어졌습니다.\n");
      out.write("\t\t\t\t\t</em>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<ul class=\"list_bullet\">\n");
      out.write("\t\t\t\t\t<li class=\"flow\">누구든지 가입이 가능합니다</li>\n");
      out.write("\t\t\t\t\t<li class=\"flow\">중고물품 거래가 가능합니다</li>\n");
      out.write("\t\t\t\t\t<li class=\"flow\">원룸 광고와 평가가 가능합니다</li>\n");
      out.write("\t\t\t\t\t<li class=\"flow\">회원은 모든 게시글에 코멘트가 가능합니다</li>\n");
      out.write("\t\t\t\t\t<li class=\"flow\">회원 간에 쪽지로 소통이 가능합니다</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"clear h40\"></div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- End main -->\n");
      out.write("\t</div>\n");
      out.write("\t<!-- END of templatemo_wrapper -->\n");
      out.write("\t\n");
      out.write("\t<!-- 각 게시판 소개 글 : 시작 -->\n");
      out.write("\t<div id=\"templatemo_bottom_wrapper\">\n");
      out.write("\t\t<div id=\"templatemo_bottom\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t<!-- market 게시판 소개 : 시작 -->\n");
      out.write("\t\t\t<div class=\"col one_fourth\">\n");
      out.write("\t\t\t\t<h4>Market Place</h4>\n");
      out.write("\t\t\t\t<ul class=\"no_bullet\">\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<span class=\"header\"> \n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=trade&pg=1&block=1\">중고거래</a>\n");
      out.write("\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t<p>각종 중고 물품 사고 팔기가 가능합니다.</p>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<span class=\"header\"> \n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=ad&pg=1&block=1\">원룸광고</a>\n");
      out.write("\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t<p>건물주분들의 원룸광고를 지원해주며, 학생분들은 원룸 정보를 알아 볼 수 있습니다.</p></li>\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<span class=\"header\"> \n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=report&pg=1&block=1\">사건/사고 신고</a>\n");
      out.write("\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t<p>거래 중의 각종 사고를 신고할 수 있습니다. 불량 이용자는 블랙리스트에 등록됩니다.</p>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- market 게시판 소개 : 끝 -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- board 게시판 소개 : 시작 -->\n");
      out.write("\t\t\t<div class=\"col one_fourth\">\n");
      out.write("\t\t\t\t<h4>Board</h4>\n");
      out.write("\t\t\t\t<ul class=\"no_bullet\">\n");
      out.write("\t\t\t\t\t<li><span class=\"header\"> <a\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=free&pg=1&block=1\"\">자유게시판</a>\n");
      out.write("\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t<p>모든 이용자들이 자유롭게 대화할 수 있는 게시판 입니다.</p></li>\n");
      out.write("\t\t\t\t\t<li><span class=\"header\"> <a\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=none&pg=1&block=1\">익명게시판</a>\n");
      out.write("\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t<p>무엇이든 터놓고 이야기 할 수 있는 게시판입니다.</p></li>\n");
      out.write("\t\t\t\t\t<li><span class=\"header\"> <a\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=missing&pg=1&block=1\">분실/습득물</a>\n");
      out.write("\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t<p>교내에서 분실/습득한 물품을 신고해주세요</p></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- board 게시판 소개 : 끝 -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- gallery 게시판 소개 : 시작 -->\n");
      out.write("\t\t\t<div class=\"col one_fourth\">\n");
      out.write("\t\t\t\t<h4>Photo Gallery</h4>\n");
      out.write("\t\t\t\t<ul class=\"footer_gallery\">\n");
      out.write("\t\t\t\t\t<!-- DB에서 최신 이미지 9개 가져와서 출력 -->\n");
      out.write("\t\t\t\t\t");
 List list = (List)request.getAttribute("list");
						
						for(int i=0; i<list.size(); i++){
							GalleryDto dto = (GalleryDto)list.get(i);
					
      out.write("\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/src/db/gallery/");
      out.print(dto.getUrl());
      out.write("\" rel=\"lightbox[portfolio]\"> \n");
      out.write("\t\t\t\t\t\t\t<img src=\"");
      out.print(commonURL);
      out.write("/src/db/gallery/");
      out.print(dto.getUrl());
      out.write("\" alt=\"image 6\" />\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/gallery/list.do?pg=1&block=1\" class=\"more\">more</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- gallery 게시판 소개 : 끝 -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- Contact 페이지 소개 : 시작 -->\n");
      out.write("\t\t\t<div class=\"col one_fourth no_margin_right\">\n");
      out.write("\t\t\t\t<h4>Contact</h4>\n");
      out.write("\t\t\t\t<ul class=\"no_bullet\">\n");
      out.write("\t\t\t\t\t<!-- <li><span class=\"header\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/blog.do\">Blog</a>\n");
      out.write("\t\t\t\t\t\t</span> \n");
      out.write("\t\t\t\t\t\t<p>관리자 전용 블로그입니다. 일상생활, 유용한정보 등 다양한 포스팅을 열람하실 수 있습니다.</p>\n");
      out.write("\t\t\t\t\t</li> -->\n");
      out.write("\t\t\t\t\t<li><span class=\"header\"> \n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/contact.do\">Contact</a>\n");
      out.write("\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t<p>사이트 이용 중 불편한 사항을 관리자에게 문의 할 수 있습니다.</p></li>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<li><span class=\"header\"> \n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/admin.do\">관리자 페이지</a>\n");
      out.write("\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t<p>사이트 관리 페이지로, 권리자 권한이 있는 계정만 사용 가능합니다.</p></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- Contact 페이지 소개 : 끝 -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<!-- footer -->\n");
      out.write("\t");
      out.write("\n");
      out.write("<div id=\"templatemo_footer_wrapper\">\n");
      out.write("\t<div id=\"templatemo_footer\">\n");
      out.write("\t\t<p>\n");
      out.write("\t\t\tCopyright © 2014 All rights reserved by <a href=\"mailto:\"></a>.<br /> 이\n");
      out.write("\t\t\t웹페이지는 <a href=\"https://www.google.com/intl/ko/chrome/browser/features.html\">Chrome</a>\n");
      out.write("\t\t\t브라우저에 최적화 되어 있습니다.<br/>\n");
      out.write("\t\t</p>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- END of templatemo_footer -->\n");
      out.write("</div>\n");
      out.write("<!-- END of templatemo_footer_wrapper -->");
      out.write("\n");
      out.write("\t\n");
      out.write("\t<!-- slider script -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/jquery.nivo.slider.pack.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t$(window).load(function() {\n");
      out.write("\t\t\t$('#slider').nivoSlider({\n");
      out.write("\t\t\t\tcontrolNav : true\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
