/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-11-30 13:11:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hoseo.member.*;
import java.util.*;
import com.hoseo.util.StringUtil;

public final class correction_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/src/jsp/member/../../include/footer.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/member/../../include/header.jsp", Long.valueOf(1417078158611L));
    _jspx_dependants.put("/src/jsp/member/../../include/common.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/member/../../include/head.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/member/../../include/checkLogin_MvIndex.jsp", Long.valueOf(1417351615973L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write('\n');

	if (session.getAttribute("userid") == null) {

      out.write("\n");
      out.write("<script>\n");
      out.write("\talert(\"로그인 후 이용하실 수 있습니다.\");\n");
      out.write("\tlocation.replace(\"/hoseo/index.do\");\n");
      out.write("</script>\n");

	return;
	}

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');

	//상대경로 대용
	String commonURL="/hoseo";

      out.write("\n");
      out.write("\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\t<title>Hoseo Community</title>\n");
      out.write("\t\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/templatemo_style.css\" type=\"text/css\"/>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/top_navi.css\" type=\"text/css\"/>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/button.css\" type=\"text/css\"/>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/img_expend.css\" type=\"text/css\" media=\"screen\"/>\n");
      out.write("\n");
      out.write("\t<!--<script src=\"http://code.jqeury.com/jqeury-latest.min.js\"></script> -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/naviSlider_imgModal.js\"></script>\t\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/top_navi_silder.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<!-- 상단 메뉴 드롭다운 -->\n");
      out.write("\t<script language=\"javascript\" type=\"text/javascript\">\n");
      out.write("\t\tddsmoothmenu.init({\n");
      out.write("\t\t\tmainmenuid: \"templatemo_menu\", //menu DIV id\n");
      out.write("\t\t\torientation: 'h', //Horizontal or vertical menu: Set to \"h\" or \"v\"\n");
      out.write("\t\t\tclassname: 'ddsmoothmenu', //class added to menu's outer DIV\n");
      out.write("\t\t\t//customtheme: [\"#1c5a80\", \"#18374a\"],\n");
      out.write("\t\t\tcontentsource: \"markup\" //\"markup\" or [\"container_id\", \"path_to_menu_file\"]\n");
      out.write("\t\t})\n");
      out.write("\n");
      out.write("\t\tfunction clearText(field)\n");
      out.write("\t\t{\n");
      out.write("    \t\tif (field.defaultValue == field.value) \n");
      out.write("    \t\t\tfield.value = '';\n");
      out.write("    \t\telse if (field.value == '') \n");
      out.write("    \t\t\tfield.value = field.defaultValue;\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\t\n");
      out.write("\t<script type=\"text/JavaScript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/img_modal.js\"></script>");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/join.css\"\n");
      out.write("\ttype=\"text/css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/login.css\"\n");
      out.write("\ttype=\"text/css\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div id=\"templatemo_wrapper\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!-- header -->\n");
      out.write("\t\t");
      out.write('\n');
      out.write('\n');
      out.write('\n');

	String userid = StringUtil.convNull(
			(String) session.getAttribute("userid"), "");
	String username = StringUtil.convNull(
			(String) session.getAttribute("username"), "");
	String layout = StringUtil.convNull(
			(String) request.getAttribute("layout"), "index");

	System.out.println("Session_userid : " + userid);
	System.out.println("Session_username : " + username);
	System.out.println(layout);
	
	
	

      out.write("\n");
      out.write("<!-- Start_header -->\n");
      out.write("<div id=\"templatemo_header\">\n");
      out.write("\t<div id=\"site_title\">\n");
      out.write("\t\t<img src=\"");
      out.print(commonURL);
      out.write("/src/images/add/intro_tex02.jpg\"\n");
      out.write("\t\t\talt=\"Venture1st_호서대학교\" />\n");
      out.write("\t</div>\n");
      out.write("\t<div align=\"right\" style=\"color: orange;\">\n");
      out.write("\t\t이 웹페이지는 <a\n");
      out.write("\t\t\thref=\"https://www.google.com/intl/ko/chrome/browser/features.html\">Chrome</a>\n");
      out.write("\t\t브라우저에 최적화 되어 있습니다\n");
      out.write("\t</div>\n");
      out.write("\t</a>\n");
      out.write("\t<div id=\"templatemo_search\">\n");
      out.write("\t\t<form action=\"search.do\" method=\"get\">\n");
      out.write("\t\t\t<input type=\"text\" value=\"Search...\" name=\"keyword\" id=\"keyword\"\n");
      out.write("\t\t\t\ttitle=\"keyword\" onfocus=\"clearText(this)\" onblur=\"clearText(this)\"\n");
      out.write("\t\t\t\tclass=\"txt_field\" /> <input type=\"submit\" name=\"Search\" value=\"\"\n");
      out.write("\t\t\t\talt=\"Search\" id=\"searchbutton\" title=\"Search\" class=\"sub_btn\" />\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!-- End_header -->\n");
      out.write("\n");

	

      out.write("\n");
      out.write("\n");
      out.write("<!-- Start Menu -->\n");
      out.write("<div id=\"templatemo_menu\" class=\"ddsmoothmenu\">\n");
      out.write("\t<ul>\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/index.do\"\n");
      out.write("\t\t\t");
if (layout.equals("index")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Home</a></li>\n");
      out.write("\t\t<li><a\n");
      out.write("\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=trade&pg=1&block=1\"\n");
      out.write("\t\t\t");
if (layout.equals("market")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Market\n");
      out.write("\t\t\t\tPlace</a>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=trade&pg=1&block=1\">중고\n");
      out.write("\t\t\t\t\t\t거래</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=ad&pg=1&block=1\">원룸 광고</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=report&pg=1&block=1\">사건/사고\n");
      out.write("\t\t\t\t\t\t신고</a></li>\n");
      out.write("\t\t\t</ul></li>\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=free&pg=1&block=1\"\n");
      out.write("\t\t\t");
if (layout.equals("board")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Board</a>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=free&pg=1&block=1\">자유게시판</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=none&pg=1&block=1\">익명게시판</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=missing&pg=1&block=1\">분실/습득물</a></li>\n");
      out.write("\t\t\t</ul></li>\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/gallery/list.do?pg=1&block=1\"\n");
      out.write("\t\t\t");
if (layout.equals("gallery")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Gallery</a></li>\n");
      out.write("\t\t<!-- <li><a href=\"blog.jsp\">Blog</a></li> -->\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/contact.do\"\n");
      out.write("\t\t\t");
if (layout.equals("contact")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Contact</a></li>\n");
      out.write("\t</ul>\n");
      out.write("\n");
      out.write("\t");

		if (!userid.equals("")) {
	
      out.write("\n");
      out.write("\t<div align=\"right\">\n");
      out.write("\t\t<div style=\"color: #fff\">\n");
      out.write("\t\t\t");
      out.print(username);
      out.write("&nbsp;님&nbsp;\n");
      out.write("\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/message/message_receive.do\">마이페이지</a>&nbsp;&nbsp;&nbsp; \n");
      out.write("\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/member/logout.do\" class=\"button button-blue\"><span>로그아웃</span></a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t");

		} else {
	
      out.write("\n");
      out.write("\t<div align=\"right\">\n");
      out.write("\t\t<a href=\"");
      out.print(commonURL);
      out.write("/member/login.do\" class=\"button button-blue\"><span>로그인</span></a>\n");
      out.write("\t\t<a href=\"");
      out.print(commonURL);
      out.write("/member/register.do\" class=\"button button-blue\"><span>회원가입</span></a>\n");
      out.write("\t</div>\n");
      out.write("\t");

		}
	
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<br style=\"clear: left\" />\n");
      out.write("</div>\n");
      out.write("<!-- End Menu -->");
      out.write("\n");
      out.write("\n");
      out.write("\t\t");

			MemberDto dto = (MemberDto) request
					.getAttribute("result_correction");
			MemberDto dto_pw = (MemberDto) request
					.getAttribute("Modify_password");
		
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div id=\"templatemo_main\">\n");
      out.write("\t\t\t<form name=\"join\" method=\"post\" class=\"form-horizontal\">\n");
      out.write("\t\t\t\t<div align=\"center\" class=\"login_form\">\n");
      out.write("\t\t\t\t\t<div class=\"login_here\">\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(commonURL);
      out.write("/src/images/add/intro_tex03.png\"\n");
      out.write("\t\t\t\t\t\t\talt=\"호서대학교\"></img>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div style=\"width: 400px;\">\n");
      out.write("\t\t\t\t\t\t<div class=\"row_group\">\n");
      out.write("\t\t\t\t\t\t\t<div id=\"idDiv\" class=\"join_row\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"ps_box int_id\"> <!-- userid -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<div align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(userid);
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</div> <input type=\"hidden\" name=\"userid\" value=\"");
      out.print(userid);
      out.write("\"></input>\n");
      out.write("\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"join_row\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"ps_box int_pass\"> <!-- password1 --> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"password\" name=\"pwf1\" id=\"pwf1\" maxlength=\"16\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"현재 비밀번호\" class=\"int input_pw\"\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"check('pwf1')\" />\n");
      out.write("\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t<div align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"error\" name=\"pwf1_result\" id=\"pwf1_result\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- \n");
      out.write("\t\t\t\t\t\t비밀번호 입력부분 -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"join_row\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"ps_box int_pass\"> <!-- password1 --> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"password\" name=\"pw1\" id=\"pw1\" maxlength=\"16\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"비밀번호\" class=\"int input_pw\"\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"correction_check('pw1')\" />\n");
      out.write("\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t<div align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"error\" name=\"pw1_result\" id=\"pw1_result\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"join_row\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"ps_box int_pass\"> <!-- password2 --> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"password\" name=\"pw2\" id=\"pw2\" maxlength=\"16\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"비밀번호 재입력\" class=\"int input_pw\"\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"correction_check('pw2')\" />\n");
      out.write("\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t<div align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"error\" name=\"pw2_result\" id=\"pw2_result\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"row_group\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"join_row\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"ps_box\"> <!-- username --> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"username\" id=\"username\" maxlength=\"10\"\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=");
      out.print(dto.getUsername());
      out.write(" placeholder=\"닉네임\" class=\"int\"\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"check('username')\" />\n");
      out.write("\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t<div align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"error\" name=\"username_result\" id=\"username_result\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- 생년월일 자르기 -->\n");
      out.write("\t\t\t\t\t\t\t");

								String bir = dto.getBirth();
								String year = bir.substring(0, 4);
								String month = bir.substring(5, 7).replace("0", ""); 
								String day = bir.substring(8, 10);
								int to = Integer.parseInt(month); 
							
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"join_row join_birthday\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"join_birth\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"bir_yy\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"ps_box\"> <!-- birth_year --> <input\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"year\" id=\"year\" maxlength=\"4\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=");
      out.print(year);
      out.write(" placeholder=\"생년\" class=\"int\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonblur=\"checkBirth()\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"bir_mm\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"ps_box\"> <!-- birth_month --> <select\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle=\"월\" name=\"month\" id=\"month\" class=\"sel\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonblur=\"checkBirth()\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">▒선택▒</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"01\" ");
if(to==1){ 
      out.write(" selected ");
}
      out.write(" >1 </option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"02\" ");
if(to==2){ 
      out.write(" selected ");
}
      out.write(" >2 </option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"03\" ");
if(to==3){ 
      out.write(" selected ");
}
      out.write(" >3</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"04\"  ");
if(to==4){ 
      out.write(" selected ");
}
      out.write(" >4</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"05\"  ");
if(to==5){ 
      out.write(" selected ");
}
      out.write(" >5</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"06\" ");
if(to==6){ 
      out.write(" selected ");
}
      out.write(" >6</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"07\" ");
if(to==7){ 
      out.write(" selected ");
}
      out.write(" >7</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"08\"");
if(to==8){ 
      out.write(" selected ");
}
      out.write(">8</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"09\" ");
if(to==9){ 
      out.write(" selected ");
}
      out.write(" >9</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"10\" ");
if(to==10){ 
      out.write(" selected ");
}
      out.write(" >10</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"11\" ");
if(to==11){ 
      out.write(" selected ");
}
      out.write(" >11</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"12\" ");
if(to==12){ 
      out.write(" selected ");
}
      out.write("  >12</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"bir_dd\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"ps_box\"> <!-- birth_day --> <input\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"day\" id=\"day\" maxlength=\"2\" placeholder=\"일\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=");
      out.print(day);
      out.write(" class=\"int\" onblur=\"checkBirth()\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"error\" name=\"birth_result\" id=\"birth_result\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"join_row join_email\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"ps_box int_email\"> <!-- email --> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"email\" name=\"email\" id=\"email\" maxlength=\"100\"\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=");
      out.print(dto.getEmail());
      out.write(" placeholder=\"이메일\" class=\"int\"\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"check('email')\" />\n");
      out.write("\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t<div align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"error\" name=\"email_result\" id=\"email_result\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"row_group\" style=\"display: block\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"join_row join_mobile\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"ps_box country_code\"> <span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"sel_value\">+82</span>\n");
      out.write("\t\t\t\t\t\t\t\t</span> <span class=\"ps_box int_mobile\"> <!-- phone --> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"phone\" id=\"phone\" maxlength=\"11\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"휴대전화번호\" class=\"int\"\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"check('phone')\"\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(dto.getPhone().trim());
      out.write("\" />\n");
      out.write("\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t<div align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"error\" name=\"phone_result\" id=\"phone_result\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:checkPhone()\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn_c btn_mobile_submit\">인증</a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div id=\"authnoDiv\" class=\"join_row join_mobile_certify\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"ps_box int_mobile_certify\"> <!-- phone_key -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"key\" id=\"key\" maxlength=\"6\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"인증번호\" class=\"int\" onblur=\"check('key')\" />\n");
      out.write("\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t<div align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"error\" name=\"key_result\" id=\"key_result\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:checkKey()\" class=\"btn_c btn_mobile_submit\">확인</a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div id=\"main\" style=\"margin: auto;\">\n");
      out.write("\t\t\t\t\t\t<div id=a style=\"float: center;\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"수정하기\" class=\"thoughtbot\"\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"modify_ok()\" />\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div id=b style=\"float: center;\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:history.back() \"><input type=\"button\"\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"뒤로가기 \" class=\"thoughtbot\" /></a> </a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"clear h20\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- END of templatemo_main -->\n");
      out.write("\t</div>\n");
      out.write("\t<!-- END of templatemo_wrapper -->\n");
      out.write("\t<div class=\"clear h40\"></div>\n");
      out.write("\t<!-- footer -->\n");
      out.write("\t");
      out.write("\n");
      out.write("<div id=\"templatemo_footer_wrapper\">\n");
      out.write("\t<div id=\"templatemo_footer\">\n");
      out.write("\t\t<p>\n");
      out.write("\t\t\tCopyright © 2014 All rights reserved by <a href=\"mailto:\"></a>.<br /> 이\n");
      out.write("\t\t\t웹페이지는 <a href=\"https://www.google.com/intl/ko/chrome/browser/features.html\">Chrome</a>\n");
      out.write("\t\t\t브라우저에 최적화 되어 있습니다.<br/>\n");
      out.write("\t\t</p>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- END of templatemo_footer -->\n");
      out.write("</div>\n");
      out.write("<!-- END of templatemo_footer_wrapper -->");
      out.write("\n");
      out.write("\t<script type=\"text/JavaScript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/member.js\"></script>\n");
      out.write("\t<script>\n");
      out.write("\t\t// 개인정보 수정하기\n");
      out.write("\t\tfunction modify_ok() {\n");
      out.write("\n");
      out.write("\t\t\tvar username = document.getElementById(\"username\").value;\n");
      out.write("\n");
      out.write("\t\t\tvar year = document.getElementById(\"year\").value;\n");
      out.write("\t\t\tvar month = document.getElementById(\"month\").value;\n");
      out.write("\t\t\tvar day = document.getElementById(\"day\").value;\n");
      out.write("\n");
      out.write("\t\t\tvar email = document.getElementById(\"email\").value;\n");
      out.write("\t\t\tvar phone = document.getElementById(\"phone\").value;\n");
      out.write("\n");
      out.write("\t\t\tif (username == \"\") {\n");
      out.write("\t\t\t\talert(\"닉네임을 확인해주세요\");\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif (year == \"\") {\n");
      out.write("\t\t\t\talert(\"생년 확인 해주세요\");\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif (month == \"\") {\n");
      out.write("\t\t\t\talert(\"월 확인해주세요\");\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif (day == \"\") {\n");
      out.write("\t\t\t\talert(\"일 확인해주세요\");\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif (email == \"\") {\n");
      out.write("\t\t\t\talert(\"이메일을 확인해주세요\");\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif (phone == \"\") {\n");
      out.write("\t\t\t\talert(\"핸드폰 번호를 확인해주세요\");\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\talert(\"회원정보 수정완료. index 페이지로 이동 합니다.\");\n");
      out.write("\n");
      out.write("\t\t\tvar frm = document.join;\n");
      out.write("\t\t\tfrm.action = \"./modify_ok.do\";\n");
      out.write("\t\t\tfrm.submit();\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction correction_check(id) {\n");
      out.write("\t\t\t// 입력 값 받아오기\n");
      out.write("\t\t\tvar id = document.getElementById(id).id;\n");
      out.write("\t\t\tvar value = document.getElementById(id).value;\n");
      out.write("\n");
      out.write("\t\t\t// 출력 input 설정\n");
      out.write("\t\t\tvar rootTag = document.getElementById(id + \"_result\");\n");
      out.write("\n");
      out.write("\t\t\t// 입력 값이 없을 때\n");
      out.write("\t\t\tif ((id == \"pw1\" || id == \"pw2\") && value == \"\") {\n");
      out.write("\t\t\t\trootTag.innerHTML = \"미입력시 현재비밀번호로 저장됩니다.\";\n");
      out.write("\t\t\t\trootTag.value = id;\n");
      out.write("\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
