/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-11-29 09:55:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hoseo.util.StringUtil;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/src/jsp/member/rules_1.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/member/../../include/footer.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/member/rules_2.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/member/../../include/header.jsp", Long.valueOf(1417078158611L));
    _jspx_dependants.put("/src/jsp/member/../../include/common.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/member/../../include/head.jsp", Long.valueOf(1417067248000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<!-- 헤더파일 include -->\n");
      out.write('\n');
      out.write('\n');
      out.write('\n');

	//상대경로 대용
	String commonURL="/hoseo";

      out.write("\n");
      out.write("\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\t<title>Hoseo Community</title>\n");
      out.write("\t\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/templatemo_style.css\" type=\"text/css\"/>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/top_navi.css\" type=\"text/css\"/>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/button.css\" type=\"text/css\"/>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/img_expend.css\" type=\"text/css\" media=\"screen\"/>\n");
      out.write("\n");
      out.write("\t<!--<script src=\"http://code.jqeury.com/jqeury-latest.min.js\"></script> -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/naviSlider_imgModal.js\"></script>\t\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/top_navi_silder.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<!-- 상단 메뉴 드롭다운 -->\n");
      out.write("\t<script language=\"javascript\" type=\"text/javascript\">\n");
      out.write("\t\tddsmoothmenu.init({\n");
      out.write("\t\t\tmainmenuid: \"templatemo_menu\", //menu DIV id\n");
      out.write("\t\t\torientation: 'h', //Horizontal or vertical menu: Set to \"h\" or \"v\"\n");
      out.write("\t\t\tclassname: 'ddsmoothmenu', //class added to menu's outer DIV\n");
      out.write("\t\t\t//customtheme: [\"#1c5a80\", \"#18374a\"],\n");
      out.write("\t\t\tcontentsource: \"markup\" //\"markup\" or [\"container_id\", \"path_to_menu_file\"]\n");
      out.write("\t\t})\n");
      out.write("\n");
      out.write("\t\tfunction clearText(field)\n");
      out.write("\t\t{\n");
      out.write("    \t\tif (field.defaultValue == field.value) \n");
      out.write("    \t\t\tfield.value = '';\n");
      out.write("    \t\telse if (field.value == '') \n");
      out.write("    \t\t\tfield.value = field.defaultValue;\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\t\n");
      out.write("\t<script type=\"text/JavaScript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/img_modal.js\"></script>");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div id=\"templatemo_wrapper\">\n");
      out.write("\t\n");
      out.write("\t\t<!-- 상단 네비바 -->\n");
      out.write("\t\t");
      out.write('\n');
      out.write('\n');
      out.write('\n');

	String userid = StringUtil.convNull(
			(String) session.getAttribute("userid"), "");
	String username = StringUtil.convNull(
			(String) session.getAttribute("username"), "");
	String layout = StringUtil.convNull(
			(String) request.getAttribute("layout"), "index");

	System.out.println("Session_userid : " + userid);
	System.out.println("Session_username : " + username);
	System.out.println(layout);
	
	
	

      out.write("\n");
      out.write("<!-- Start_header -->\n");
      out.write("<div id=\"templatemo_header\">\n");
      out.write("\t<div id=\"site_title\">\n");
      out.write("\t\t<img src=\"");
      out.print(commonURL);
      out.write("/src/images/add/intro_tex02.jpg\"\n");
      out.write("\t\t\talt=\"Venture1st_호서대학교\" />\n");
      out.write("\t</div>\n");
      out.write("\t<div align=\"right\" style=\"color: orange;\">\n");
      out.write("\t\t이 웹페이지는 <a\n");
      out.write("\t\t\thref=\"https://www.google.com/intl/ko/chrome/browser/features.html\">Chrome</a>\n");
      out.write("\t\t브라우저에 최적화 되어 있습니다\n");
      out.write("\t</div>\n");
      out.write("\t</a>\n");
      out.write("\t<div id=\"templatemo_search\">\n");
      out.write("\t\t<form action=\"search.do\" method=\"get\">\n");
      out.write("\t\t\t<input type=\"text\" value=\"Search...\" name=\"keyword\" id=\"keyword\"\n");
      out.write("\t\t\t\ttitle=\"keyword\" onfocus=\"clearText(this)\" onblur=\"clearText(this)\"\n");
      out.write("\t\t\t\tclass=\"txt_field\" /> <input type=\"submit\" name=\"Search\" value=\"\"\n");
      out.write("\t\t\t\talt=\"Search\" id=\"searchbutton\" title=\"Search\" class=\"sub_btn\" />\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!-- End_header -->\n");
      out.write("\n");

	

      out.write("\n");
      out.write("\n");
      out.write("<!-- Start Menu -->\n");
      out.write("<div id=\"templatemo_menu\" class=\"ddsmoothmenu\">\n");
      out.write("\t<ul>\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/index.do\"\n");
      out.write("\t\t\t");
if (layout.equals("index")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Home</a></li>\n");
      out.write("\t\t<li><a\n");
      out.write("\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=trade&pg=1&block=1\"\n");
      out.write("\t\t\t");
if (layout.equals("market")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Market\n");
      out.write("\t\t\t\tPlace</a>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=trade&pg=1&block=1\">중고\n");
      out.write("\t\t\t\t\t\t거래</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=ad&pg=1&block=1\">원룸 광고</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=report&pg=1&block=1\">사건/사고\n");
      out.write("\t\t\t\t\t\t신고</a></li>\n");
      out.write("\t\t\t</ul></li>\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=free&pg=1&block=1\"\n");
      out.write("\t\t\t");
if (layout.equals("board")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Board</a>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=free&pg=1&block=1\">자유게시판</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=none&pg=1&block=1\">익명게시판</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=missing&pg=1&block=1\">분실/습득물</a></li>\n");
      out.write("\t\t\t</ul></li>\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/gallery/list.do?pg=1&block=1\"\n");
      out.write("\t\t\t");
if (layout.equals("gallery")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Gallery</a></li>\n");
      out.write("\t\t<!-- <li><a href=\"blog.jsp\">Blog</a></li> -->\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/contact.do\"\n");
      out.write("\t\t\t");
if (layout.equals("contact")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Contact</a></li>\n");
      out.write("\t</ul>\n");
      out.write("\n");
      out.write("\t");

		if (!userid.equals("")) {
	
      out.write("\n");
      out.write("\t<div align=\"right\">\n");
      out.write("\t\t<div style=\"color: #fff\">\n");
      out.write("\t\t\t");
      out.print(username);
      out.write("&nbsp;님&nbsp;\n");
      out.write("\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/message/message_receive.do\">마이페이지</a>&nbsp;&nbsp;&nbsp; \n");
      out.write("\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/member/logout.do\" class=\"button button-blue\"><span>로그아웃</span></a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t");

		} else {
	
      out.write("\n");
      out.write("\t<div align=\"right\">\n");
      out.write("\t\t<a href=\"");
      out.print(commonURL);
      out.write("/member/login.do\" class=\"button button-blue\"><span>로그인</span></a>\n");
      out.write("\t\t<a href=\"");
      out.print(commonURL);
      out.write("/member/register.do\" class=\"button button-blue\"><span>회원가입</span></a>\n");
      out.write("\t</div>\n");
      out.write("\t");

		}
	
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<br style=\"clear: left\" />\n");
      out.write("</div>\n");
      out.write("<!-- End Menu -->");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<form name=\"agree\" method=\"post\">\n");
      out.write("\t\t<div id=\"templatemo_main\">\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<h5><small>회원가입약관</small></h5>\n");
      out.write("\t\t\t\t");
      out.write("\n");
      out.write("<textarea rows=\"15\" readonly style=\"width: 920px; border-width: 1; border-color: rgb(204, 204, 204); border-style: solid; padding: 20px; font-size: 11px;\">\n");
      out.write("[일반 회원가입 이용 약관] \n");
      out.write("\n");
      out.write("제 1 조 (목적)\n");
      out.write("\n");
      out.write("이 약관은 전기통신사업법령 및 정보 통신망 이용촉진 및 정보보호 등에 관한 법령에 의하여 호서대 커뮤니티(이하 \"회사\"라 한다)와 회사가 제공하는 서비스(이하 \"서비스\"라 한다)를 이용함에 있어 이용조건 및 절차에 관한 기본적인 사항을 규정하는 것을 목적으로 하며 서비스 이용자(이하 \"회원\"이라 한다)가 소정의 절차를 거쳐서 \"동의함\"을 누르면 본 약관에 동의하는 것으로 간주한다.\n");
      out.write("\n");
      out.write("제 2 조 (약관의 효력 및 변경)\n");
      out.write("\n");
      out.write("1. 이 약관은 그 내용을 회사가 서비스 화면을 통해 게시하고 회원이 동의를 함으로써 효력을 발생한다. \n");
      out.write("2. 회사는 약관의 규제 등에 관한 법률, 전기통신사업법령, 정보통신망 이용촉진 및 정보 보호 등에 관한 법률 등 관련법을 위배하지 않는 범위에서 이 약관을 정할 수 있으며 필요 시 약관을 개정할 수 있다. 또한 변경된 약관에 이의가 있는 이용자는 회사가 정한 양식에 따라 언제든지 탈퇴할 수 있다.\n");
      out.write("3. 회사는 이 약관의 시행을 위하여 필요한 세부 시행 사항을 별도로 정할 수 있다.\n");
      out.write("\n");
      out.write("제 3 조 (약관 외 준칙)\n");
      out.write("\n");
      out.write("이 약관에서 정하지 않은 사항과 이 약관의 해석에 관하여는 정부가 제정한 전기통신기본법,전기통신 사업법, 정보통신망 이용촉진 및 정보보호 등에 관한 법률 및 기타 관계법령 또는 상관례에 따른다. \n");
      out.write("\n");
      out.write("제 4 조 (회원가입)\n");
      out.write("\n");
      out.write("1. 회원 회사가 정한 양식에 따라 회원정보를 성실히 기입하고, 약관에 동의한다는 의사표시를 함으로서 회원가입을 신청하며 회사는 이를 회사가 정한 확인절차를 거쳐 회원가입을 승낙한다.\n");
      out.write("2. 회사는 제1항과 같이 회원 가입을 신청한 회원 중 다음 각 호에 해당하지 않는 한 회원으로 등록한다.\n");
      out.write("1) 등록 내용에 허위, 기재누락, 오기가 있는 경우 및 비 실명 가입\n");
      out.write("2) 기타 회원으로 등록하는 것이 회사의 서비스에 현저히 지장이 있다고 판단되는 경우\n");
      out.write("\n");
      out.write("제 5 조 (회원정보 변경)\n");
      out.write("\n");
      out.write("회원은 이용 신청 시 기재한 회원정보가 변경되었을 경우 온라인으로 직접 수정해야 하며, 관리자에게 수정을 요구할 수 없습니다. 이때 변경하지 않은 정보로 인해 발생되는 문제는 회원에게 책임이 있습니다.\n");
      out.write("\n");
      out.write("제 6 조 (회원 탈퇴 및 자격 상실, 서비스 이용제한 등) \n");
      out.write("\n");
      out.write("1. 회원은 탈퇴를 희망하는 경우 요청할 수 있으며 회사가 정한 방법에 의하여 회사는 탈퇴를 즉시 처리한다.\n");
      out.write("2. 회원이 다음 각 호의 사유에 해당하는 경우, 회원자격을 제한 및 정지시킬 수 있습니다.\n");
      out.write("1) 가입 신청 시에 허위 내용을 등록한 경우 및 회사가 정한 실명 확인을 거치지 않은 비 실명 가입\n");
      out.write("2) 다른 사람의 서비스 이용을 방해하거나 타인의 명예를 훼손하는 것, 그 정보를 도용하는 등 전자거래 및 정보통신서비스 이용질서를 위협하는 경우\n");
      out.write("3) 제공되는 정보를 변경하는 등 회사의 운영을 방해한 경우\n");
      out.write("4) 법령과 본 약관이 금지하거나 미풍양속에 반하는 행위를 하는 경우 및 회사가 정한 이용조건에 위배되는 경우\n");
      out.write("4. 회사의 회원자격 및 서비스 이용을 제한 정지 시킨 후 그 사유가 시정되지 아니하는 경우 회사는 회원자격을 상실 시킬 수 있다.\n");
      out.write("\n");
      out.write("제 7 조 (서비스 이용시간 및 중단)\n");
      out.write("\n");
      out.write("1. 서비스의 이용은 회사가 업무상 또는 기술상 특별한 경우를 제외하고는 연중무휴 1일 24시간 동안 제공하는 것을 원칙으로 한다. \n");
      out.write("다만, 운영상의 목적으로 회사가 정한 기간에는 서비스가 일시 중지될 수 있다. 이런 경우 회사는 사전 또는 사후 이를 공지한다.\n");
      out.write("2. 회사는 다음 각 호에 해당하는 경우 서비스 제공을 중지할 수 있다. \n");
      out.write("1) 서비스용 설비의 보수 등 공사로 인한 부득이한 경우 \n");
      out.write("2) 전기통신사업법에 규정된 기간통신사업자가 전기통신 서비스를 중지했을 경우\n");
      out.write("3) 설비 장애 또는 이용 폭주 등으로 서비스 이용에 지장이 있는 경우\n");
      out.write("4) 해킹 사고 등 기타, 불가 항력적 사유가 있는 경우\n");
      out.write("5) 정기적인 시스템 점검 및 유지, 보수의 경우\n");
      out.write("\n");
      out.write("제 8 조(이용자에 대한 통지)\n");
      out.write("\n");
      out.write("1. 회사는 회원이 서비스 이용 중 필요하다고 인정되는 다양한 정보에 대해서 전자메일이나 기타 방법 등으로 회원에게 정보를 제공할 수 있다.\n");
      out.write("2. 회사는 불특정다수 회원에 대한 통지의 경우 1주일 이상 게시판에 게시 함으로서 개별 통지에 갈음할 수 있다.\n");
      out.write("\n");
      out.write("제 9 조 (회원의 개인정보, 아이디 및 비밀번호에 대한 의무)\n");
      out.write("\n");
      out.write("1. 회원은 서비스 이용을 위해 등록할 경우 현재의 사실과 일치하는 완전한 정보(이하 \"등록정보\"라 한다)를 제공하셔야 합니다. 또한 등록정보에 변경이 발생할 경우 즉시 갱신해야 한다. 회원이 제공하는 정보의 내용이 허위(차명, 비 실명 등)인 것으로 판명되거나, 그러하다고 의심할 만한 합리적인 사유가 발생할 경우 회사는 회원의 본 서비스 사용을 일부 또는 전부 중지할 수 있으며, 이로 인해 발생하는 불이익에 대해 책임을 지지 않는다\n");
      out.write("3. 회원이 불법으로 타인의 개인 정보를 게시, 전송, 입수하였거나 전자메일 기타 다른 수단에 의하여 게시, 전송 또는 입수한 모든 형태의 정보에 대하여는 회원이 모든 책임을 부담하며 회사는 어떠한 책임도 부담하지 아니한다 \n");
      out.write("\n");
      out.write("제 10 조 (회원 게시물)\n");
      out.write("\n");
      out.write("1. 게시물에 대한 저작권을 포함한 모든 권리 및 책임은 이를 게시한 회원에게 있으며 회사는 서비스 내의 모든 게재권을 갖는다.\n");
      out.write("2. 회사는 회원 서비스에 게재한 정보의 정확성 및 신뢰도 등 내용에 대해서는 책임을 지지 않는다.\n");
      out.write("3. 회사는 회원이 서비스에 게시, 게재하거나 서비스를 통해 전송, 수신한 내용물 및 그 결과에 대하여 책임지지 않으며, 아래 사항에 해당하는 경우 게시물을 임의로 삭제 할 수 있다.\n");
      out.write("가. 타인을 비방하거나, 프라이버시를 침해하거나, 명예를 손상시키는 내용인 경우\n");
      out.write("나. 공공질서 및 미풍양속에 위반되는 내용인 경우\n");
      out.write("다. 서비스의 안정적인 운영에 지장을 주거나 줄 우려가 있는 경우\n");
      out.write("라. 범죄행위에 관련된다고 판단되는 내용인 경우\n");
      out.write("마. 회사의 지적재산권, 타인의 지적재산권 등 기타 권리를 침해하는 내용인 경우\n");
      out.write("바. 특정제품의 선전 등 기타 상용 목적으로 게시되는 내용인 경우\n");
      out.write("사. 입력된 정보를 무단 개조하는 경우\n");
      out.write("아. 타 회원의 회원 아이디, 비밀번호를 도용하는 경우\n");
      out.write("자. 게시판의 목적에 맞지 않는 사이버 시위 및 도배 목적의 내용인 경우\n");
      out.write("차. 기타 관계법령에 위반된다고 판단되는 경우 \n");
      out.write("\n");
      out.write("제 11 조 (지적소유권의 보호)\n");
      out.write("\n");
      out.write("1. 회사가 작성한 저작물에 대한 저작권 및 기타 지적재산권은 모두 회사에 귀속되며 서비스 외에서의 복제, 전송, 배포 등의 일체의 이용은 금지된다. \n");
      out.write("2. 회원은 서비스를 이용하여 얻은 정보를 가공, 판매하는 행위 등 서비스에 게재된 자료를 상업적으로 이용할 수 없다.\n");
      out.write("\n");
      out.write("제 12 조 (개인정보보호 및 보안관리)\n");
      out.write("\n");
      out.write("1. 회사의 개인정보보호정책은 정보통신망 이용촉진 및 정보보호 등에 관한 법률 규정을 준수한다.\n");
      out.write("2. 회사는 회원의 개인정보가 분실, 도난, 누출, 변조 또는 훼손되지 않도록 안전성 확보에 필요한 조치를 강구한다. 단, 회원이 게시판이나 email, 채팅 등 온라인 상에서 자발적으로 제공하는 개인정보는 다른 사람이 수집하여 사용할 가능성이 있으며 이러한 위험은 개인에게 책임이 있고 회사는 책임이 없다.\n");
      out.write("\n");
      out.write("제 13 조 (회원정보 사용에 대한 동의)\n");
      out.write("\n");
      out.write("1. 회사는 온라인에서 제공하는 서비스를 이용하는 회원을 대상으로 해당 서비스의 양적, 질적 향상을 위하여 회원의 개인 식별이 가능한 개인정보를 이용자의 동의를 받아, 이를 수집하여 맞춤 서비스, 인터넷 웹서비스, 커뮤니케이션 서비스, 이벤트, 뉴스메일진 등에 이용할 수 있다\n");
      out.write("2. 회사가 수집하는 개인정보는 서비스의 제공에 필요한 최소한으로 하되, 필요한 경우 보다 더 자세한 정보를 요구할 수 있다.\n");
      out.write("3. 회원 제공한 개인정보는 회원의 동의 없이 제3자에게 누설하거나 제공하지 않는다. 단, 회사는 비즈니스 파트너와의 제휴를 통해 회원에게 제공되는 서비스 질을 향상 시키기 위해서 회원 가입 시 입력 받은 개인정보로부터 이름이나 주소와 같은 서비스 이용에 필요한 제한된 범위의 개인정보를 이용할 수 있다. 이 때 이용자의 동의는 본 약관에 동의한 것으로서 갈음할 수 있다.\n");
      out.write("4. 회원은 회사에 제공한 개인정보의 수집과 이용에 대한 동의를 언제든지 철회할 수 있다. \n");
      out.write("\n");
      out.write("제 14 조 (쿠키[cookie] 이용방법) \n");
      out.write("\n");
      out.write("쿠키(cookie)는 웹사이트 서버가 사용자의 브라우저에 보내는 작은 데이터로 사용자 컴퓨터 하드디스크에 저장된다.\n");
      out.write("개인화된 (personalized) 서비스나 맞춤화된(customized) 서비스를 이용하기 위해서는 사용자가 쿠키를 허용해야 한다. 쿠키를 이용하면 회원이 방문한 서비스 뿐만 아니라 방문횟수 및 이용형태를 파악할 수 있으며 좀더 유용하고 편리한 맞춤 서비스를 제공하는데 도움이 된다.\n");
      out.write("물론 쿠키에 대한 선택권은 회원이 가지고 있으며 브라우저에서 옵션을 선택함으로써 모든 쿠키를 허용하거나, 쿠키가 저장될 때마다 확인을 거치거나, 쿠키의 저장을 거부할 수 있다.\n");
      out.write("\n");
      out.write("제 15 조 (회사의 의무)\n");
      out.write("\n");
      out.write("1. 회사의 법령과 이 약관이 금지하는 행위를 하지 않으며 이 약관이 정하는 바에 따라 지속적이고, 안정적으로 서비스를 제공하는데 최선을 다하여야 한다.\n");
      out.write("2. 회사는 이용자가 안전하게 인터넷서비스를 이용할 수 있도록 이용자의 개인정보(신용정보포함)의 보호,관리를 위해 필요한 조치를 취한다.\n");
      out.write("3. 회사는 이용자가 원하지 않는 영리목적의 광고성 전자우편을 발송하지 않는다.\n");
      out.write("단, 전자 우편 수신거부는 회원이 직접 행하여야 한다.\n");
      out.write("4. 회사는 회원 개인 정보를 본인의 승낙 없이 제3자에게 누설, 배포하지 않는 것을 원칙으로 한다. 단, 아래 사항에 해당하는 경우는 예외\n");
      out.write("1) 전기통신기본법 등 법률의 규정에 의해 국가기관의 요구가 있는 경우\n");
      out.write("2) 범죄에 대한 수사상의 목적이 있거나 정보통신윤리위원회의 요청이 있는 경우\n");
      out.write("3) 기타 관계법령에서 정한 절차에 따른 요청이 있는 경우\n");
      out.write("5. 회사는 업무와 관련하여 회원 전체 또는 일부의 개인 정보에 관한 자료를 작성하여 이를 사용할 수 있고, 서비스를 통하여 회원의 컴퓨터에 쿠키를 전송할 수 있다. \n");
      out.write("\n");
      out.write("제 16 조 (회원의 의무)\n");
      out.write("\n");
      out.write("1. 회원은 이 약관에서 규정하는 모든 사항과 서비스 이용안내 및 주의사항 등을 준수하여야 한다.\n");
      out.write("2. 회원은 등록 양식에서 요구되는 내용들에 대해 진실되고 정확하며 현재의 사실과 일치되는 완전한 정보를 제공하고 유지한다. \n");
      out.write("3. 회원은 자신의 아이디와 비밀번호를 관리할 의무를 가지고, 회원의 아이디와 비밀번호를 사용하여 발생하는 모든 결과에 대한 책임은 회원에게 있다.\n");
      out.write("4. 회원은 자신의 아이디 및 비밀번호를 제3자에게 이용하게 해서는 안되며, 아이디 및 비밀번호를 도난 당하거나 제3자가 사용하고 있음을 인지한 경우에는 바로 회사에 통보하고 회사의 안내가 있는 경우에는 그에 따라야 한다.\n");
      out.write("5. 회원은 회사를 이용함으로써 얻은 정보를 승낙 없이 복제, 전송, 출판, 배포, 방송 및 기타 방법에 의하여 상업적으로 이용하거나 제3자에게 이용하게 할 수 없다. \n");
      out.write("6. 회원의 행동규범\n");
      out.write("가. 회원이 본 서비스를 통해 게재한 게시물 또는 컨텐츠에 대해서는 이용자가 책임을 진다.\n");
      out.write("나. 회원은 불법적이거나 타인에게 해를 입히거나, 타인의 명예를 훼손하는 등의 행위를 하지 않는다.\n");
      out.write("다. 회원은 타인의 개인정보를 수집 또는 저장하여 유용하지 않는다. \n");
      out.write("\n");
      out.write("제 17 조 (분쟁해결 및 기타사항)\n");
      out.write("\n");
      out.write("1. 회사는 이용자가 제기하는 정당한 의견이나 불만을 반영하여 적절하고 빠른 조치를 취한다. \n");
      out.write("2. 회사는 신속한 처리가 곤란한 경우에는 회원에게 그 사유와 처리일정을 통보한다.\n");
      out.write("\n");
      out.write("제 18 조 (손해배상책임)\n");
      out.write("\n");
      out.write("회사는 무상으로 제공하는 서비스의 이용과 관련하여 회원에게 발생한 손해에 대해 서는 책임을 지지 않는다.\n");
      out.write("\n");
      out.write("제 19 조 (면책조항)\n");
      out.write("\n");
      out.write("1. 회사는 서비스 이용 중 회사의 귀책사유가 없이 발생한 손해에 관하여 책임을 지지 않는다.\n");
      out.write("2. 회사는 약관에 명시된 사유로 인하여 서비스를 제공할 수 없는 경우에는 서비스 제공의 불이행에 관하여는 책임이 면제된다.\n");
      out.write("3. 회사는 회원의 귀책 사유로 인한 서비스 이용 장애에 대해 그 책임이 면제된다. \n");
      out.write("5. 회사는 회원이 서비스에 게재한 정보, 자료, 사실의 신뢰도, 정확성 등 그 내용에 관하여 책임이 면제된다.\n");
      out.write("6. 회사는 등록 받은 도메인이름이 상표권 등 타인의 권리를 침해한 경우 이에 대한 책임을 부담하지 아니한다. \n");
      out.write("\n");
      out.write("제 20 조 (분쟁의 처리)\n");
      out.write("\n");
      out.write("1. 회사에 귀책사유가 명백히 인정되는 경우, 회원은 회사를 상대로 소송 등을 제기하기 전에 회사가 운영하는 고객센터 등을 통해 우선 이를 알려야 하며, 이를 통해 분쟁을 해결해야 한다.\n");
      out.write("2. 회원이 회사를 상대로 소송을 제기할 경우, 상충하는 법령 또는 법규에 관계 없이 본 서비스의 이용 또는 약관으로 인하여 발생하는 모든 청구권은 청구권이 발생한 날로부터 1년 이내에 행사 되어야 하며, 이후에는 소멸된다.\n");
      out.write("\n");
      out.write("제 21 조 (관할 법원)\n");
      out.write("\n");
      out.write("회원과 회사간에 서비스로 부터 발생하거나 서비스와 관련된 모든 분쟁은 회사의 주소지를 관할하는 법원을 합의 관할로 한다. \n");
      out.write("\n");
      out.write("부 칙\n");
      out.write("\n");
      out.write("제1조 (시행일) ① 이 약관은 2007년 1월 1일부터 시행한다.\n");
      out.write("</textarea>");
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div align=\"center\">\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"chk1\" id=\"chk1\" value=\"1\" /><label for=\"chk1\">회원가입 약관을 읽었으며 내용에 동의합니다.</label>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"clear h40\"></div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<h5><small>개인정보보호정책</small></h5>\n");
      out.write("\t\t\t\t");
      out.write("\n");
      out.write("<textarea rows=\"15\" readonly style=\"width: 920px; border-width: 1; border-color: rgb(204, 204, 204); border-style: solid; padding: 20px; font-size: 11px;\">\n");
      out.write("호서대 커뮤니티(이하 회사)는 귀하의 개인정보 보호를 매우 중요시하며, 『정보통신망 이용촉진등에 관한법률』상의 개인정보보호 규정 및 정보통신부가 제정한 『개인정보 보호지침』을 준수하고 있습니다.\n");
      out.write("\"회사\"는 개인정보보호방침을 통하여 귀하께서 제공하시는 개인정보가 어떠한 용도와 방식으로 이용되고 있으며 개인정보호를 위해 어떠한 조치가 취해지고 있는지 알려드리니다. 본 보호정책은 수시로 내용이 변경될 수 있으므로 정기적으로 방문하셔서 확인하시기 바랍니다. \n");
      out.write(" \n");
      out.write("본 개인정보 보호정책은 다음과 같은 내용을 담고 있습니다 : \n");
      out.write(" \n");
      out.write("1. \"회사\"의 개인정보의 수집목적 및 이용목적 \n");
      out.write("2. 수집하는 개인정보 항목 및 수집방법 \n");
      out.write("3. 쿠키에 의한 개인정보 수집 \n");
      out.write("4. 목적외 사용 및 제3자에 대한 제공 \n");
      out.write("5. 개인정보의 열람 및 정정 \n");
      out.write("6. 개인정보의 수집, 이용 및 제공에 대한 동의 철회 \n");
      out.write("7. 개인정보의 보유기간 및 이용기간 \n");
      out.write("8. 개인정보보호를 위한 기술적 대책 \n");
      out.write("9. 개인정보의 위탁처리 \n");
      out.write("10. 의견수렴 및 불만처리 \n");
      out.write("11. 개인정보 관리책임자 \n");
      out.write(" \n");
      out.write("1. 개인정보의 수집목적 및 이용목적\n");
      out.write(" \n");
      out.write("\"회사\"가 회원님 개인의 정보를 수집하는 목적은 \"회사\" 사이트를 통하여 회원님께 최적의 맞춤화된 서비스를 제공해드리기 위한 것입니다. \"회사\"는 각종의 컨텐츠 및 정보를 무료로 서비스해 드리고 있습니다. 이 때 회원님께서 제공해주신 개인정보를 바탕으로 회원님께 보다 더 유용한 정보를 선택적으로 제공하는 것이 가능하게 됩니다.\n");
      out.write("(1) \"회사\"는 다음과 같은 목적을 위하여 개인정보를 수집하고 있습니다. \n");
      out.write("1) 서비스제공을 위한 계약의 성립(본인식별 및 본인의사 확인등) \n");
      out.write("2) 기타 새로운 서비스, 신상품이나 이벤트 정보 안내 \n");
      out.write("(2) 단, 이용자의 기본적 인권 침해의 우려가 있는 민감한 개인정보(인종 및 민족, 사상 및 신조, 본적지, 정치적 성향 및 범죄기록, 건강상태 및 성생활등)는 수집하지 않습니다. \n");
      out.write(" \n");
      out.write("2. 수집하는 개인정보 항목 및 수집방법\n");
      out.write(" \n");
      out.write("\"회사\"는 최초 회원가입을 하실 때 서비스 제공을 위해 가장 필수적인 개인정보를 받고 있습니다. 회원가입시에 받는 정보는 회원님의 이름, 이메일, 전화번호, 주소 등입니다. 이 이외에 특정 서비스를 제공하기 위하여 추가적인 정보제공을 요청하고 있습니다.\n");
      out.write("\"회사\" 메르랩, 지사관련서비스, 포럼, 클럽, 이벤트, 사이버몰 서비스등이 그것이며, 실명확인을 위한 주민등록번호, 휴대폰번호, 기타 서비스 제공에 필요한 추가 정보의 기재를 요청하게 됩니다.\n");
      out.write("또한 설문조사나 이벤트 시에 집단적인 통계분석을 위해서나 경품발송을 위한 목적으로도 개인정보 기재를 요청할 수 있습니다. 이 때에도 기입하신 해당서비스 제공이나 회원님께 사전에 밝힌 목적 이외의 다른 어떠한 목적으로도 사용되지 않음을 알려드립니다. \n");
      out.write(" \n");
      out.write("3. 쿠키(cookie)에 의한 개인정보 수집\n");
      out.write(" \n");
      out.write("\"회사\"는 귀하에 대한 정보를 저장하고 수시로 찾아내는 '쿠키(cookie)'를 사용합니다. 쿠키는 웹사이트가 귀하의 컴퓨터 브라우저(넷스케이프, 인터넷 익스플로러 등)로 전송하는 소량의 정보입니다.\n");
      out.write("귀하께서 웹사이트에 접속을 하면 \"회사\"의 컴퓨터는 귀하의 브라우저에 있는 쿠키의 내용을 읽고, 귀하의 추가정보를 귀하의 컴퓨터에서 찾아 접속에 따른 성명 등의 추가 입력 없이 서비스를 제공할 수 있습니다.\n");
      out.write("쿠키는 귀하의 컴퓨터는 식별하지만 귀하를 개인적으로 식별하지는 않습니다. 또한 귀하는 쿠키에 대한 선택권이 있습니다. 웹브라우저의 옵션을 조정함으로써 모든 쿠키를 다 받아들이거나, 쿠키가 설치될 때 통지를 보내도록 하거나, 아니면 모든 쿠키를 거부할 수 있는 선택권을 가질 수 있습니다. \n");
      out.write(" \n");
      out.write("4. 목적외 사용 및 제3자에 대한 제공\n");
      out.write(" \n");
      out.write("\"회사\"는 귀하의 개인정보를 <개인정보의 수집목적 및 이용목적> 에서 고지한 범위내에서 사용하며, 동 범위를 초과하여 이용하거나 타인 또는 타기업, 기관에 제공하지 않습니다.\n");
      out.write("그러나 보다 나은 서비스 제공을 위하여 귀하의 개인정보를 제휴사에게 제공하거나 공유할 수 있습니다. 개인정보를 제공하거나 공유할 경우에는 사전에 귀하께 제휴사가 누구인지, 제공 또는 공유되는 개인정보항목이 무엇인지, 왜 그러한 개인정보가 제공되거나 공유되어야 하는지, 그리고 언제까지 어떻게 보호,관리되는지에 대해 개별적으로 전자우편 및 서면을 고지하여 동의를 구하는 절차를 거치게 되며, 귀하께서 동의하지 않는 경우에는 제휴사에게 제공하거나 제휴사와 공유하지 않습니다. \n");
      out.write(" \n");
      out.write("5. 개인정보의 열람 및 정정 \n");
      out.write(" \n");
      out.write("(1) 귀하는 언제든지 등록되어 있는 귀하의 개인정보를 열람하거나 정정하실 수 있습니다. 개인정보 열람 및 정정을 하고자 할 경우에는 <개인정보수정>을 클릭하여 직접 열람 또는 정정하거나 , 개인정보관리책임자에게 E-mail로 연락주시면 조치하겠습니다. \n");
      out.write("(2) 귀하가 개인정보의 오류에 대한 정정을 요청한 경우, 정정을 완료하기 전까지 당해 개인정보를 이용하지 않습니다. \n");
      out.write(" \n");
      out.write("6. 개인정보의 수집, 이용 및 제공에 대한 동의철회\n");
      out.write(" \n");
      out.write("(1) 회원가입 등을 통해 개인정보의 수집, 이용, 제공에 대해 귀하께서 동의하신 내용을 귀하는 언제든지 철회할 수 있습니다. 동의철회는 개인정보관리책임자에게 E-mail 등으로 연락하시면 즉시 개인정보의 삭제 등 필요한 조치를 하겠습니다.\n");
      out.write("(2) \"회사\"는 개인정보의 수집에 대한 동의철회(회원탈퇴)를 개인정보 수집시 동등한 방법 및 절차로 행사할 수 있도록 필요한 조치를 하겠습니다. \n");
      out.write(" \n");
      out.write("7. 개인정보보호기간 및 이용기간\n");
      out.write(" \n");
      out.write("(1) 귀하의 개인정보는 다음과 같이 개인정보의 수집목적 또는 제공받은 목적이 달성되면 파기됩니다. \n");
      out.write("1) 회원가입정보의 경우, 회원가입을 탈퇴하거나 회원에서 제명된 때 \n");
      out.write("2) 대금지급정보의 경우, 대금의 완료일 또는 채권소멸시효기간의 만료된 때 \n");
      out.write("3) 배송정보의 경우, 물품 또는 서비스가 인도되거나 제공된 때 \n");
      out.write(" \n");
      out.write("(2) 위 보유기간에도 불구하고 계속 보유하여야 할 필요가 있을 경우에도 귀하의 동의를 받겠습니다. \n");
      out.write(" \n");
      out.write("8. 개인정보보호를 위한 기술적 대책\n");
      out.write(" \n");
      out.write("\"회사\"는 귀하의 개인정보를 취급함에 개인정보가 분실, 도난, 누출, 변조 또는 훼손되지 않도록 안전성 확보를 위하여 다음과 같은 기술적 대책을 강구하고 있습니다. \n");
      out.write("(1) 귀하의 개인정보는 비밀번호에 의해 보호되며, 파일 및 전송 데이터를 암호화하거나 파일 잠금기능(Lock)을 사용하여 중요한 데이터는 별도의 보안기능을 통해 보호되고 있습니다. \n");
      out.write("(2) \"회사\"는 백신프로그램을 이용하여 컴퓨터바이러스에 의한 피해를 방지하기 위한 조치를 취하고 있습니다. 백신프로그램은 주기적으로 업데이트되며 갑작스런 바이러스가 출현할 경우 백신이 나오는 즉시 이를 제공함으로써 개인정보가 침해되는 것을 방지하고 있습니다. \n");
      out.write("(3) \"회사\"는 암호알고리즘을 이용하여 네트워크 상의 개인정보를 안전하게 전송할 수 있는 방법을 채택하고 있습니다. \n");
      out.write("(4) 해킹 등에 의해 귀하의 개인정보가 유출되는 것을 방지하기 위해, 외부로부터의 침입을 차단하는 장치를 이용하고 있습니다. \n");
      out.write(" \n");
      out.write("9. 개인정보의 위탁처리\n");
      out.write(" \n");
      out.write("\"회사\"는 서비스 향상을 위해서 귀하의 개인정보를 외부에 위탁하여 처리할 수 있습니다. \n");
      out.write("(1) 개인정보의 처리를 위탁하는 경우에는 미리 그 사실을 귀하에게 고지하겠습니다. \n");
      out.write("(2) 개인정보의 처리를 위탁하는 경우에는 위탁계약 등을 통하여 서비스제공자의 개인정보보호 관련 지시엄수, 개인정보에 관한 비밀유지, 제3자 제공의 금지 및 사고시의 책임부담 등을 명확히 규정하고 당해 계약내용을 서면 또는 전자적으로 보관하겠습니다. \n");
      out.write(" \n");
      out.write("10. 의견수렴 및 불만처리 \n");
      out.write(" \n");
      out.write("\"회사\"는 개인정보보호와 관련하여 귀하가 의견과 불만을 제기할 수 있는 창구를 개설(Q&A 및 게시판, 웹메일)하고 있습니다. \n");
      out.write("개인정보와 관련한 불만이 있으신 분은 \"회사\"의 개인정보 관리책임자에게 의견을 주시면 접수 즉시 조치하여 처리결과를 통보해 드립니다. 또는 정부에서 설치하여 운영중인 개인정보침해신고센터(http://www.cyberprivacy.or.kr, 전화 02-1336, PC통신 go epivacy)에 불만처리를 신청할 수 있습니다. \n");
      out.write(" \n");
      out.write("11. 개인정보관리책임자 \n");
      out.write(" \n");
      out.write("회원님 계정의 비밀번호에 대한 보안을 유지할 책임은 회원님 자신에게 있습니다. \"회사\"에서 메일 또는 기타 방법으로 회원님께 비밀번호를 질문하는 경우는 절대 없으므로 어떠한 경우에도 비밀번호를 알려주지 마십시오. 로그온(log-on)한 상태에서는 주위의 다른 사람에게 개인정보가 유출되지 않도록 주의를 기울이시기 바랍니다. \n");
      out.write(" \n");
      out.write("개인정보 관리 및 책임자 문의 담당자 : \n");
      out.write(" \n");
      out.write("E-MAIL: jebumud@jebumud.co.kr\n");
      out.write(" \n");
      out.write("상기 개인정보보호정책은 2007년 01월 01일부터 시행합니다. \n");
      out.write("\t\t\t\t</textarea>");
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div align=\"center\">\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"chk2\" id=\"chk2\" value=\"1\"/><label for=\"chk2\">개인정보보호정책을 읽었으며 내용에 동의합니다.</label>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"clear h20\"></div>\n");
      out.write("\t\t\t<div align=\"center\">\n");
      out.write("\t\t\t\t<input type=\"button\" class=\"thoughtbot\" value=\"동의 후 계속진행\" onclick=\"agreebtn()\"/>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t<!-- END of templatemo_main -->\n");
      out.write("\t</div>\n");
      out.write("\t<!-- END of templatemo_wrapper -->\n");
      out.write("\t\n");
      out.write("\t<div class=\"clear h40\"></div>\n");
      out.write("\t<div class=\"clear h40\"></div>\n");
      out.write("\t\n");
      out.write("\t<!-- footer -->\n");
      out.write("\t");
      out.write("\n");
      out.write("<div id=\"templatemo_footer_wrapper\">\n");
      out.write("\t<div id=\"templatemo_footer\">\n");
      out.write("\t\t<p>\n");
      out.write("\t\t\tCopyright © 2014 All rights reserved by <a href=\"mailto:\"></a>.<br /> 이\n");
      out.write("\t\t\t웹페이지는 <a href=\"https://www.google.com/intl/ko/chrome/browser/features.html\">Chrome</a>\n");
      out.write("\t\t\t브라우저에 최적화 되어 있습니다.<br/>\n");
      out.write("\t\t</p>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- END of templatemo_footer -->\n");
      out.write("</div>\n");
      out.write("<!-- END of templatemo_footer_wrapper -->");
      out.write("\n");
      out.write("\t<script>\n");
      out.write("\t//약관 동의 체크\n");
      out.write("\tfunction agreebtn() {\n");
      out.write("\t\tvar frm = document.agree;\n");
      out.write("\t\tfrm.action = \"./register_form.do\";\n");
      out.write("\n");
      out.write("\t\t/* 체크 여부 확인 */\n");
      out.write("\t\tif (!frm.chk1.checked || !frm.chk2.checked) {\n");
      out.write("\t\t\talert(\"약관동의 후 가입 가능합니다.\");\n");
      out.write("\t\t\treturn;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfrm.submit();\n");
      out.write("\t}\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
