/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-11-27 08:49:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hoseo.board.*;
import java.util.*;
import com.hoseo.page.Pager;
import com.hoseo.util.StringUtil;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/src/jsp/board/../../include/head.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/board/../../include/footer.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/board/../../include/common.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/board/../../include/header.jsp", Long.valueOf(1417078158611L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write('\n');
      out.write('\n');
      out.write('\n');

	//상대경로 대용
	String commonURL="/hoseo";

      out.write("\n");
      out.write("\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\t<title>Hoseo Community</title>\n");
      out.write("\t\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/templatemo_style.css\" type=\"text/css\"/>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/top_navi.css\" type=\"text/css\"/>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/button.css\" type=\"text/css\"/>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/img_expend.css\" type=\"text/css\" media=\"screen\"/>\n");
      out.write("\n");
      out.write("\t<!--<script src=\"http://code.jqeury.com/jqeury-latest.min.js\"></script> -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/naviSlider_imgModal.js\"></script>\t\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/top_navi_silder.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<!-- 상단 메뉴 드롭다운 -->\n");
      out.write("\t<script language=\"javascript\" type=\"text/javascript\">\n");
      out.write("\t\tddsmoothmenu.init({\n");
      out.write("\t\t\tmainmenuid: \"templatemo_menu\", //menu DIV id\n");
      out.write("\t\t\torientation: 'h', //Horizontal or vertical menu: Set to \"h\" or \"v\"\n");
      out.write("\t\t\tclassname: 'ddsmoothmenu', //class added to menu's outer DIV\n");
      out.write("\t\t\t//customtheme: [\"#1c5a80\", \"#18374a\"],\n");
      out.write("\t\t\tcontentsource: \"markup\" //\"markup\" or [\"container_id\", \"path_to_menu_file\"]\n");
      out.write("\t\t})\n");
      out.write("\n");
      out.write("\t\tfunction clearText(field)\n");
      out.write("\t\t{\n");
      out.write("    \t\tif (field.defaultValue == field.value) \n");
      out.write("    \t\t\tfield.value = '';\n");
      out.write("    \t\telse if (field.value == '') \n");
      out.write("    \t\t\tfield.value = field.defaultValue;\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\t\n");
      out.write("\t<script type=\"text/JavaScript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/img_modal.js\"></script>");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/board_slider.css\" type=\"text/css\" media=\"screen\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/board_write.css\" type=\"text/css\"/>\n");
      out.write("</head>\n");
      out.write("\n");

	String kind = request.getParameter("kind"); //현재 카테고리
	String searchKey = StringUtil.convNull(request.getParameter("searchKey"),"all"); // 검색 종류
	String keyword = StringUtil.convNull(request.getParameter("keyword"),""); // 검색어

      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div id=\"templatemo_wrapper\">\n");
      out.write("\t\t<!-- header -->\n");
      out.write("\t\t");
      out.write('\n');
      out.write('\n');
      out.write('\n');

	String userid = StringUtil.convNull(
			(String) session.getAttribute("userid"), "");
	String username = StringUtil.convNull(
			(String) session.getAttribute("username"), "");
	String layout = StringUtil.convNull(
			(String) request.getAttribute("layout"), "index");

	System.out.println("Session_userid : " + userid);
	System.out.println("Session_username : " + username);
	System.out.println(layout);
	
	
	

      out.write("\n");
      out.write("<!-- Start_header -->\n");
      out.write("<div id=\"templatemo_header\">\n");
      out.write("\t<div id=\"site_title\">\n");
      out.write("\t\t<img src=\"");
      out.print(commonURL);
      out.write("/src/images/add/intro_tex02.jpg\"\n");
      out.write("\t\t\talt=\"Venture1st_호서대학교\" />\n");
      out.write("\t</div>\n");
      out.write("\t<div align=\"right\" style=\"color: orange;\">\n");
      out.write("\t\t이 웹페이지는 <a\n");
      out.write("\t\t\thref=\"https://www.google.com/intl/ko/chrome/browser/features.html\">Chrome</a>\n");
      out.write("\t\t브라우저에 최적화 되어 있습니다\n");
      out.write("\t</div>\n");
      out.write("\t</a>\n");
      out.write("\t<div id=\"templatemo_search\">\n");
      out.write("\t\t<form action=\"search.do\" method=\"get\">\n");
      out.write("\t\t\t<input type=\"text\" value=\"Search...\" name=\"keyword\" id=\"keyword\"\n");
      out.write("\t\t\t\ttitle=\"keyword\" onfocus=\"clearText(this)\" onblur=\"clearText(this)\"\n");
      out.write("\t\t\t\tclass=\"txt_field\" /> <input type=\"submit\" name=\"Search\" value=\"\"\n");
      out.write("\t\t\t\talt=\"Search\" id=\"searchbutton\" title=\"Search\" class=\"sub_btn\" />\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!-- End_header -->\n");
      out.write("\n");

	

      out.write("\n");
      out.write("\n");
      out.write("<!-- Start Menu -->\n");
      out.write("<div id=\"templatemo_menu\" class=\"ddsmoothmenu\">\n");
      out.write("\t<ul>\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/index.do\"\n");
      out.write("\t\t\t");
if (layout.equals("index")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Home</a></li>\n");
      out.write("\t\t<li><a\n");
      out.write("\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=trade&pg=1&block=1\"\n");
      out.write("\t\t\t");
if (layout.equals("market")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Market\n");
      out.write("\t\t\t\tPlace</a>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=trade&pg=1&block=1\">중고\n");
      out.write("\t\t\t\t\t\t거래</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=ad&pg=1&block=1\">원룸 광고</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=report&pg=1&block=1\">사건/사고\n");
      out.write("\t\t\t\t\t\t신고</a></li>\n");
      out.write("\t\t\t</ul></li>\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=free&pg=1&block=1\"\n");
      out.write("\t\t\t");
if (layout.equals("board")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Board</a>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=free&pg=1&block=1\">자유게시판</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=none&pg=1&block=1\">익명게시판</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=missing&pg=1&block=1\">분실/습득물</a></li>\n");
      out.write("\t\t\t</ul></li>\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/gallery/list.do?pg=1&block=1\"\n");
      out.write("\t\t\t");
if (layout.equals("gallery")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Gallery</a></li>\n");
      out.write("\t\t<!-- <li><a href=\"blog.jsp\">Blog</a></li> -->\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/contact.do\"\n");
      out.write("\t\t\t");
if (layout.equals("contact")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Contact</a></li>\n");
      out.write("\t</ul>\n");
      out.write("\n");
      out.write("\t");

		if (!userid.equals("")) {
	
      out.write("\n");
      out.write("\t<div align=\"right\">\n");
      out.write("\t\t<div style=\"color: #fff\">\n");
      out.write("\t\t\t");
      out.print(username);
      out.write("&nbsp;님&nbsp;\n");
      out.write("\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/message/message_receive.do\">마이페이지</a>&nbsp;&nbsp;&nbsp; \n");
      out.write("\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/member/logout.do\" class=\"button button-blue\"><span>로그아웃</span></a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t");

		} else {
	
      out.write("\n");
      out.write("\t<div align=\"right\">\n");
      out.write("\t\t<a href=\"");
      out.print(commonURL);
      out.write("/member/login.do\" class=\"button button-blue\"><span>로그인</span></a>\n");
      out.write("\t\t<a href=\"");
      out.print(commonURL);
      out.write("/member/register.do\" class=\"button button-blue\"><span>회원가입</span></a>\n");
      out.write("\t</div>\n");
      out.write("\t");

		}
	
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<br style=\"clear: left\" />\n");
      out.write("</div>\n");
      out.write("<!-- End Menu -->");
      out.write("\n");
      out.write("\t\t<div id=\"templatemo_main\">\n");
      out.write("\t\t\t<div class=\"board_title\">\n");
      out.write("\t\t\t\t<h3 style=\"text-align: center;\">\n");
      out.write("\t\t\t\t\t");
if(kind.equals("trade")){ 
      out.write("중고 거래 게시판");
} 
					else if(kind.equals("ad")){ 
      out.write("원룸 광고 게시판");
}
					else if(kind.equals("report")){ 
      out.write("사건/사고 신고 게시판");
} 
					else if(kind.equals("free")){ 
      out.write("자유 게시판");
} 
					else if(kind.equals("none")){ 
      out.write("익명 게시판");
} 
					else if(kind.equals("missing")){ 
      out.write("분실 / 습득물 신고 게시판");
} 
      out.write("\n");
      out.write("\t\t\t\t</h3>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- 프리미엄 게시글 영역 : 시작 -->\n");
      out.write("\t\t\t");
if(kind.equals("report")) {
      out.write("\n");
      out.write("\t\t\t<div align=\"left\" class=\"report_img\">\n");
      out.write("\t\t\t\t<a href=\"http://thecheat.co.kr/rb/?m=bbs&bid=cheat&type=cheat&page_num=1\" target=\"_block\">\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(commonURL);
      out.write("/src/images/add/joonggonara_main_banner.jpg\" alt=\"더치트 사기꾼 목록 확인하기\" /></a>\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t");
} else { 
      out.write("\n");
      out.write("\t\t\t<div id=\"gallery\" class=\"pl3\">\n");
      out.write("\t\t\t\t<div id=\"t\"> \n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t");
 List premium = (List)request.getAttribute("premium");
					
						if(premium.size()>0){
					
						for(int i=0; i<premium.size(); i++){
							BoardDto dto = (BoardDto)premium.get(i);
						
      out.write("\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col one_fourth gallery_box\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"img_frame img_frame_14 img_nom\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span></span> \t\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/src/db/board/");
      out.print(dto.getFilename1());
      out.write("\" rel=\"lightbox[new_gallery]\"> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"hot_label\" src=\"");
      out.print(commonURL);
      out.write("/src/images/add/icon_hot.png\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"hot pro_ov\" src=\"");
      out.print(commonURL);
      out.write("/src/images/add/pro_ov.png\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"hot\" src=\"");
      out.print(commonURL);
      out.write("/src/db/board/");
      out.print(dto.getFilename1());
      out.write("\" alt=\"");
      out.print(dto.getFilename1());
      out.write("\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<span></span> \n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"hot_a\" href=\"view.do?category=");
      out.print(kind);
      out.write("&seq=");
      out.print(dto.getSeq());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5><small>");
      out.print(dto.getTitle());
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
if(dto.getReplecount() > 0){
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span style=\"color: orange;\">&nbsp;&nbsp;[");
      out.print(dto.getReplecount());
      out.write("]</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</small></h5></a>\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"float: left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t");
if(kind.equals("none")){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t익명\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} else {
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">");
      out.print(dto.getUsername());
      out.write("</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"float: right\">★추천 ");
      out.print(dto.getLikecount());
      out.write("개&nbsp;&nbsp;</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</li>\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");
	
						}} else {
						
      out.write("\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-bottom: 30px;\"></div>\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
if(premium.size()>4){ 
      out.write("\n");
      out.write("\t\t\t<div align=\"center\">\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"skip\">◀ PREV</button>&nbsp;&nbsp;\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"skip\">NEXT ▶</button>\n");
      out.write("\t\t\t</div>\t\t\t\n");
      out.write("\t\t\t<!-- 프리미엄 게시글 영역 : 끝 -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- 프리미엄 게시글 슬라이더 javascript -->\n");
      out.write("\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/slider.js\"></script>\n");
      out.write("\t\t\t");
}} 
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- 일반 게시글 영역 : 시작 -->\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<table class=\"table_board\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n");
      out.write("\t\t\t\t\t<colgroup>\n");
      out.write("\t\t\t\t\t\t<col width=\"60\" />\n");
      out.write("\t\t\t\t\t\t<col width=\"*\" />\n");
      out.write("\t\t\t\t\t\t<col width=\"120\" />\n");
      out.write("\t\t\t\t\t\t<col width=\"100\" />\n");
      out.write("\t\t\t\t\t\t<col width=\"60\" />\n");
      out.write("\t\t\t\t\t\t<col width=\"60\" />\n");
      out.write("\t\t\t\t\t</colgroup>\n");
      out.write("\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t<tr class=\"tr_board\">\n");
      out.write("\t\t\t\t\t\t\t<td>번호</td>\n");
      out.write("\t\t\t\t\t\t\t<td>제목</td>\n");
      out.write("\t\t\t\t\t\t\t<td>작성자</td>\n");
      out.write("\t\t\t\t\t\t\t<td>작성일</td>\n");
      out.write("\t\t\t\t\t\t\t<td>조회</td>\n");
      out.write("\t\t\t\t\t\t\t<td>추천</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t");

						int rowCount = (Integer)request.getAttribute("rowCount");
						int pg = Integer.parseInt(request.getParameter("pg"));
					
						List list = (List)request.getAttribute("list");
					
						for(int i=0; i<list.size(); i++){
							BoardDto dto = (BoardDto)list.get(i);
					
      out.write("\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\">");
      out.print(rowCount - (((pg-1)*10)+i));
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t<td align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"view.do?category=");
      out.print(kind);
      out.write("&seq=");
      out.print(dto.getSeq());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(dto.getTitle());
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									if(dto.getPremium() > 0){
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"");
      out.print(commonURL);
      out.write("/src/images/add/icon_hot.gif\" alt=\"[Hot]\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t");
if(dto.getReplecount() > 0){
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<span style=\"color: orange;\">&nbsp;&nbsp;[");
      out.print(dto.getReplecount());
      out.write("]</span>\n");
      out.write("\t\t\t\t\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t");
if(kind.equals("none")){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t익명\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} else {
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">");
      out.print(dto.getUsername());
      out.write("</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\">");
      out.print(dto.getWdate());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\">");
      out.print(dto.getHit());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\">");
      out.print(dto.getLikecount() );
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");

			if(list.size() == 0){
      out.write("\n");
      out.write("\t\t\t\t<div style=\"text-align: center; margin: 50px;\">\n");
      out.write("\t\t\t\t등록된 게시글이 없습니다.\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t<!-- 일반 게시글 영역 : 끝 -->\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- 페이징 영역  : 시작 -->\n");
      out.write("\t\t\t<div class=\"pagging\">\n");
      out.write("\t\t\t\t");
      out.print(Pager.makeTag(commonURL + "/" + layout + "/list.do?kind=" + kind + "&", 10, searchKey, keyword));
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<form method=\"get\" action=\"list.do?\">\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"kind\" value=\"");
      out.print(kind);
      out.write("\"/>\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"pg\" value=\"1\"/>\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"block\" value=\"1\"/>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div align=\"right\" class=\"search_select\">\n");
      out.write("\t\t\t\t\t<select name=\"searchKey\" id=\"searchKey\">\n");
      out.write("\t\t\t\t\t\t<option value=\"all\" ");
if(searchKey.equals("all")){ 
      out.write("selected");
} 
      out.write(">전체</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"title\" ");
if(searchKey.equals("title")){ 
      out.write("selected");
} 
      out.write(">제목</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"contents\" ");
if(searchKey.equals("contents")){ 
      out.write("selected");
} 
      out.write(">내용</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"writer\" ");
if(searchKey.equals("writer")){ 
      out.write("selected");
} 
      out.write(">작성자</option>\n");
      out.write("\t\t\t\t\t</select> \n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"keyword\" id=\"keyword\" value=\"");
      out.print(keyword);
      out.write("\"/>\n");
      out.write("\t\t\t\t\t<button class=\"kboard-default-button-small\">검색</button>&nbsp;\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/board/write.do?layout=");
      out.print(layout);
      out.write("&category=");
      out.print(kind);
      out.write("\" class=\"kboard-default-button-small\">글쓰기</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- 페이징 영역 : 끝 -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"clear h40\"></div>\n");
      out.write("\t\t\t<div class=\"clear h40\"></div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- END of templatemo_main -->\n");
      out.write("\t</div>\n");
      out.write("\t<!-- END of templatemo_wrapper -->\n");
      out.write("\n");
      out.write("\t<!-- footer -->\n");
      out.write("\t");
      out.write("\n");
      out.write("<div id=\"templatemo_footer_wrapper\">\n");
      out.write("\t<div id=\"templatemo_footer\">\n");
      out.write("\t\t<p>\n");
      out.write("\t\t\tCopyright © 2014 All rights reserved by <a href=\"mailto:\"></a>.<br /> 이\n");
      out.write("\t\t\t웹페이지는 <a href=\"https://www.google.com/intl/ko/chrome/browser/features.html\">Chrome</a>\n");
      out.write("\t\t\t브라우저에 최적화 되어 있습니다.<br/>\n");
      out.write("\t\t</p>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- END of templatemo_footer -->\n");
      out.write("</div>\n");
      out.write("<!-- END of templatemo_footer_wrapper -->");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
