/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-11-30 13:47:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hoseo.board.BoardDto;
import com.hoseo.util.StringUtil;

public final class board_005fwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/src/jsp/board/../../include/head.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/board/../../include/footer.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/board/../../include/checkLogin.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/board/../../include/common.jsp", Long.valueOf(1417067248000L));
    _jspx_dependants.put("/src/jsp/board/../../include/header.jsp", Long.valueOf(1417078158611L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write('\n');
      out.write('\n');

	if (session.getAttribute("userid") == null) {

      out.write("\n");
      out.write("<script>\n");
      out.write("\talert(\"로그인 후 이용하실 수 있습니다.\");\n");
      out.write("\thistory.back(-1);\n");
      out.write("</script>\n");

	return;
	}

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');

	//상대경로 대용
	String commonURL="/hoseo";

      out.write("\n");
      out.write("\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\t<title>Hoseo Community</title>\n");
      out.write("\t\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/templatemo_style.css\" type=\"text/css\"/>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/top_navi.css\" type=\"text/css\"/>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/button.css\" type=\"text/css\"/>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/img_expend.css\" type=\"text/css\" media=\"screen\"/>\n");
      out.write("\n");
      out.write("\t<!--<script src=\"http://code.jqeury.com/jqeury-latest.min.js\"></script> -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/naviSlider_imgModal.js\"></script>\t\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/top_navi_silder.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<!-- 상단 메뉴 드롭다운 -->\n");
      out.write("\t<script language=\"javascript\" type=\"text/javascript\">\n");
      out.write("\t\tddsmoothmenu.init({\n");
      out.write("\t\t\tmainmenuid: \"templatemo_menu\", //menu DIV id\n");
      out.write("\t\t\torientation: 'h', //Horizontal or vertical menu: Set to \"h\" or \"v\"\n");
      out.write("\t\t\tclassname: 'ddsmoothmenu', //class added to menu's outer DIV\n");
      out.write("\t\t\t//customtheme: [\"#1c5a80\", \"#18374a\"],\n");
      out.write("\t\t\tcontentsource: \"markup\" //\"markup\" or [\"container_id\", \"path_to_menu_file\"]\n");
      out.write("\t\t})\n");
      out.write("\n");
      out.write("\t\tfunction clearText(field)\n");
      out.write("\t\t{\n");
      out.write("    \t\tif (field.defaultValue == field.value) \n");
      out.write("    \t\t\tfield.value = '';\n");
      out.write("    \t\telse if (field.value == '') \n");
      out.write("    \t\t\tfield.value = field.defaultValue;\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\t\n");
      out.write("\t<script type=\"text/JavaScript\" src=\"");
      out.print(commonURL);
      out.write("/src/js/img_modal.js\"></script>");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(commonURL);
      out.write("/src/css/board_write.css\" type=\"text/css\"/>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div id=\"templatemo_wrapper\">\n");
      out.write("\t\t<!-- header -->\n");
      out.write("\t\t");
      out.write('\n');
      out.write('\n');
      out.write('\n');

	String userid = StringUtil.convNull(
			(String) session.getAttribute("userid"), "");
	String username = StringUtil.convNull(
			(String) session.getAttribute("username"), "");
	String layout = StringUtil.convNull(
			(String) request.getAttribute("layout"), "index");

	System.out.println("Session_userid : " + userid);
	System.out.println("Session_username : " + username);
	System.out.println(layout);
	
	
	

      out.write("\n");
      out.write("<!-- Start_header -->\n");
      out.write("<div id=\"templatemo_header\">\n");
      out.write("\t<div id=\"site_title\">\n");
      out.write("\t\t<img src=\"");
      out.print(commonURL);
      out.write("/src/images/add/intro_tex02.jpg\"\n");
      out.write("\t\t\talt=\"Venture1st_호서대학교\" />\n");
      out.write("\t</div>\n");
      out.write("\t<div align=\"right\" style=\"color: orange;\">\n");
      out.write("\t\t이 웹페이지는 <a\n");
      out.write("\t\t\thref=\"https://www.google.com/intl/ko/chrome/browser/features.html\">Chrome</a>\n");
      out.write("\t\t브라우저에 최적화 되어 있습니다\n");
      out.write("\t</div>\n");
      out.write("\t</a>\n");
      out.write("\t<div id=\"templatemo_search\">\n");
      out.write("\t\t<form action=\"search.do\" method=\"get\">\n");
      out.write("\t\t\t<input type=\"text\" value=\"Search...\" name=\"keyword\" id=\"keyword\"\n");
      out.write("\t\t\t\ttitle=\"keyword\" onfocus=\"clearText(this)\" onblur=\"clearText(this)\"\n");
      out.write("\t\t\t\tclass=\"txt_field\" /> <input type=\"submit\" name=\"Search\" value=\"\"\n");
      out.write("\t\t\t\talt=\"Search\" id=\"searchbutton\" title=\"Search\" class=\"sub_btn\" />\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!-- End_header -->\n");
      out.write("\n");

	

      out.write("\n");
      out.write("\n");
      out.write("<!-- Start Menu -->\n");
      out.write("<div id=\"templatemo_menu\" class=\"ddsmoothmenu\">\n");
      out.write("\t<ul>\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/index.do\"\n");
      out.write("\t\t\t");
if (layout.equals("index")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Home</a></li>\n");
      out.write("\t\t<li><a\n");
      out.write("\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=trade&pg=1&block=1\"\n");
      out.write("\t\t\t");
if (layout.equals("market")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Market\n");
      out.write("\t\t\t\tPlace</a>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=trade&pg=1&block=1\">중고\n");
      out.write("\t\t\t\t\t\t거래</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=ad&pg=1&block=1\">원룸 광고</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/market/list.do?kind=report&pg=1&block=1\">사건/사고\n");
      out.write("\t\t\t\t\t\t신고</a></li>\n");
      out.write("\t\t\t</ul></li>\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=free&pg=1&block=1\"\n");
      out.write("\t\t\t");
if (layout.equals("board")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Board</a>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=free&pg=1&block=1\">자유게시판</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=none&pg=1&block=1\">익명게시판</a></li>\n");
      out.write("\t\t\t\t<li><a rel=\"nofollow\"\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(commonURL);
      out.write("/board/list.do?kind=missing&pg=1&block=1\">분실/습득물</a></li>\n");
      out.write("\t\t\t</ul></li>\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/gallery/list.do?pg=1&block=1\"\n");
      out.write("\t\t\t");
if (layout.equals("gallery")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Gallery</a></li>\n");
      out.write("\t\t<!-- <li><a href=\"blog.jsp\">Blog</a></li> -->\n");
      out.write("\t\t<li><a href=\"");
      out.print(commonURL);
      out.write("/contact.do\"\n");
      out.write("\t\t\t");
if (layout.equals("contact")) {
      out.write(" class=\"selected\" ");
}
      out.write(">Contact</a></li>\n");
      out.write("\t</ul>\n");
      out.write("\n");
      out.write("\t");

		if (!userid.equals("")) {
	
      out.write("\n");
      out.write("\t<div align=\"right\">\n");
      out.write("\t\t<div style=\"color: #fff\">\n");
      out.write("\t\t\t");
      out.print(username);
      out.write("&nbsp;님&nbsp;\n");
      out.write("\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/message/message_receive.do\">마이페이지</a>&nbsp;&nbsp;&nbsp; \n");
      out.write("\t\t\t<a href=\"");
      out.print(commonURL);
      out.write("/member/logout.do\" class=\"button button-blue\"><span>로그아웃</span></a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t");

		} else {
	
      out.write("\n");
      out.write("\t<div align=\"right\">\n");
      out.write("\t\t<a href=\"");
      out.print(commonURL);
      out.write("/member/login.do\" class=\"button button-blue\"><span>로그인</span></a>\n");
      out.write("\t\t<a href=\"");
      out.print(commonURL);
      out.write("/member/register.do\" class=\"button button-blue\"><span>회원가입</span></a>\n");
      out.write("\t</div>\n");
      out.write("\t");

		}
	
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<br style=\"clear: left\" />\n");
      out.write("</div>\n");
      out.write("<!-- End Menu -->");
      out.write('\n');
      out.write('	');
      out.write('	');

			String mode = StringUtil.convNull(request.getAttribute("mode"), "ins"); // 글쓰기 모드 (삽입, 수정, 답글)
			String referer = request.getHeader("referer"); // 이전 페이지
			String category = request.getParameter("category"); // 카테고리
			String writer = (String)session.getAttribute("userid"); // 작성자 아이디
			
			String title = ""; // 글제목
			String contents = ""; // 글내용
			int seq = 0; // 글번호
			
			// 수정
			if(mode.equals("mod")){
				BoardDto modDto = (BoardDto)request.getAttribute("dto");
				title = modDto.getTitle();
				contents = modDto.getContents();
				seq = (Integer)request.getAttribute("seq");
			}
		
      out.write("\n");
      out.write("\n");
      out.write("\t\t<form name=\"write_form\" id=\"frm\" action=\"write_ok.do\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"category\" id=\"category\" value=\"");
      out.print(category);
      out.write("\"/>\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"referer\" id=\"referer\" value=\"");
      out.print(referer);
      out.write("\"/>\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"writer\" id=\"writer\" value=\"");
      out.print(writer);
      out.write("\"/>\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"mode\" value=\"");
      out.print(mode);
      out.write("\"/>\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"seq\" value=\"");
      out.print(seq);
      out.write("\"/>\n");
      out.write("\n");
      out.write("\t\t\t<!-- Start main -->\n");
      out.write("\t\t\t<div id=\"templatemo_main\">\n");
      out.write("\t\t\t\t<div id=\"kboard-default-editor\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"kboard-header\"></div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"kboard-attr-row kboard-attr-title\">\n");
      out.write("\t\t\t\t\t\t<label class=\"attr-name\">제목 </label>\n");
      out.write("\t\t\t\t\t\t<div class=\"attr-value\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"title\" id=\"title\" value=\"");
      out.print(title);
      out.write("\"/>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t");

						if((category.equals("trade") || category.equals("ad")) && mode.equals("ins")){ 
					
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"kboard-attr-row\">\n");
      out.write("\t\t\t\t\t\t<label class=\"attr-name\">프리미엄 옵션 </label>\n");
      out.write("\t\t\t\t\t\t<div class=\"attr-value\">\n");
      out.write("\t\t\t\t\t\t\t<select title=\"프리미엄\" name=\"premium\" id=\"premium\" class=\"sel\" onchange=\"block_file(this)\">\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"0\">선택 안함</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1\">1주 - 1,000원</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"2\">2주 - 1,800원</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"3\">3주 - 2,500원</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"4\">4주 - 3,500원</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t&nbsp;프리미엄을 선택 시, 화면에 보일 사진을 등록해주세요.\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"attr-value\" id=\"file\" style=\"display: none\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"file\" name=\"files[0]\" id=\"files1\" onchange=\"uploadImg(this);\"/>※ 10MB 이하의 이미지 파일(jpg, gif, png)만 업로드 가능\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t");
}else{
      out.write("\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"premium\" id=\"premium\" value=\"0\"/>\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"kboard-content\">\n");
      out.write("\t\t\t\t\t\t<textarea name=\"contents\" id=\"contents\">");
      out.print(contents);
      out.write("</textarea><br/>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"kboard-control\">\n");
      out.write("\t\t\t\t\t\t<div class=\"left\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:history.back(-1)\" class=\"kboard-default-button-small\" onclick=\"history.back(-1)\">돌아가기</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"right\">\n");
      out.write("\t\t\t\t\t\t\t<a id=\"savebutton\" class=\"kboard-default-button-small\">\n");
      out.write("\t\t\t\t\t\t\t");
if(mode.equals("mod")){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t수정완료\n");
      out.write("\t\t\t\t\t\t\t");
}else{ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t작성완료\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\n");
      out.write("\t\t<!-- SmartEditer -->\n");
      out.write("\t\t<script>\n");
      out.write("\t\t$(function() {\n");
      out.write("\t\t\t//전역변수선언\n");
      out.write("\t\t\tvar editor_object = [];\n");
      out.write("\n");
      out.write("\t\t\tnhn.husky.EZCreator.createInIFrame({\n");
      out.write("\t\t\t\toAppRef : editor_object, elPlaceHolder : \"contents\", sSkinURI : \"");
      out.print(request.getContextPath());
      out.write("/src/smarteditor/SmartEditor2Skin.html\", htParams : {\n");
      out.write("\t\t\t\t\t\t\t\t// 툴바 사용 여부 (true:사용/ false:사용하지 않음)\n");
      out.write("\t\t\t\t\t\t\t\tbUseToolbar : true,\n");
      out.write("\t\t\t\t\t\t\t\t// 입력창 크기 조절바 사용 여부 (true:사용/ false:사용하지 않음)\n");
      out.write("\t\t\t\t\t\t\t\tbUseVerticalResizer : true,\n");
      out.write("\t\t\t\t\t\t\t\t// 모드 탭(Editor | HTML | TEXT) 사용 여부 (true:사용/ false:사용하지 않음)\n");
      out.write("\t\t\t\t\t\t\t\tbUseModeChanger : true,\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t//전송버튼 클릭이벤트\n");
      out.write("\t\t\t\t$(\"#savebutton\").click(\n");
      out.write("\t\t\t\t\t\tfunction() {\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\tvar title = document.getElementById(\"title\").value;\n");
      out.write("\t\t\t\t\t\t\tif (title == \"\" || title == null) {\n");
      out.write("\t\t\t\t\t\t\t\talert(\"제목을 입력해주세요.\");\n");
      out.write("\t\t\t\t\t\t\t\tfrm.title.focus();\n");
      out.write("\t\t\t\t\t\t\t\treturn;\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t//id가 smarteditor인 textarea에 에디터에서 대입\n");
      out.write("\t\t\t\t\t\t\teditor_object.getById[\"contents\"].exec(\"UPDATE_CONTENTS_FIELD\", []);\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t// 이부분에 에디터 validation 검증\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t//폼 submit\n");
      out.write("\t\t\t\t\t\t\t$(\"#frm\").submit();\n");
      out.write("\t\t\t\t\t\t})\n");
      out.write("\t\t\t})\n");
      out.write("\t\t</script>\n");
      out.write("\n");
      out.write("\t<div class=\"clear h40\"></div>\n");
      out.write("\t<div class=\"clear h40\"></div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t<!-- End main -->\n");
      out.write("\t<!-- END of templatemo_wrapper -->\n");
      out.write("\n");
      out.write("\t");
      out.write("\n");
      out.write("<div id=\"templatemo_footer_wrapper\">\n");
      out.write("\t<div id=\"templatemo_footer\">\n");
      out.write("\t\t<p>\n");
      out.write("\t\t\tCopyright © 2014 All rights reserved by <a href=\"mailto:\"></a>.<br /> 이\n");
      out.write("\t\t\t웹페이지는 <a href=\"https://www.google.com/intl/ko/chrome/browser/features.html\">Chrome</a>\n");
      out.write("\t\t\t브라우저에 최적화 되어 있습니다.<br/>\n");
      out.write("\t\t</p>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- END of templatemo_footer -->\n");
      out.write("</div>\n");
      out.write("<!-- END of templatemo_footer_wrapper -->");
      out.write("\n");
      out.write("\t<script>\n");
      out.write("\t\tdocument.getElementById(\"title\").focus();\n");
      out.write("\t</script>\n");
      out.write("\t\n");
      out.write("\t<script>\n");
      out.write("\t\t// 프리미엄 게시글 이미지 div 창 출력 조절\n");
      out.write("\t\tfunction block_file(select) {\n");
      out.write("\t\t\tvar file = document.getElementById(\"file\");\n");
      out.write("\n");
      out.write("\t\t\tif (select.value > 0)\n");
      out.write("\t\t\t\tfile.style.display = 'block';\n");
      out.write("\t\t\telse\n");
      out.write("\t\t\t\tfile.style.display = 'none';\n");
      out.write("\t\t}\n");
      out.write("\t</script>\t\n");
      out.write("\t<script src=\"");
      out.print(commonURL);
      out.write("/src/js/board.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/src/smarteditor/js/HuskyEZCreator.js\" charset=\"utf-8\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
